import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {"tr": tr, "en": en};
  Map<String, String> get tr => {
        "تنشيط الوضع اليلي": "Gece Modunu Aktif Et",
        "الإعدادات": "Ayarlar",
        "انقر هنا لاختيار الوضع اليلي": "Gece Modunu Seçmek İçin Tıklayın",
        "تشفيل صوت الاشعارات": "Bildirim Sesi Etkinleştir",
        "عند تفعيل هذا الخيار سيتم تشفيل صوت الاشعارات":
            "Bu seçeneği etkinleştirdiğinizde, bildirim sesi etkinleştirilecektir",
        "لغة البرنامج": "Uygulama Dili",
        "قم بإختيار لغة البرنامج المناسبة لك": "Size uygun uygulama dili seçin",
        "عالي  20 قأكثر يوميا": "Yüksek 20 veya daha fazla günlük",
        "متوسط  11-19  يوميا": "Orta 11-19 günlük",
        "منخفض  5-10  يوميا": "Düşük 5-10 günlük",
        "نادر  1-5  يوميا": "Nadir 1-5 günlük",
        "غير مسموح": "İzin verilmiyor",
        "لا يمكنك تغيير الاشعارات الخاصة بهذه الصلاة": "Bu namazın bildirimlerini değiştiremezsiniz",
        "حسنا": "Tamam",
        "المنبه": "Alarm",
        "تذكير الاحاديث": "Hadis Hatırlatıcısı",
        "الأذكار اليومية": "Günlük Zikirler",
        "قراءة القرآن": "Kuran Okuma",
        "اوقات الصيام": "Oruç Zamanları",
        "اوقات الاذان": "Namaz Vakitleri",
        "أذكار عشوائية": "Rastgele Zikirler",
        "سيصلك اشعار بذكر عشوائي": "Rastgele bir zikir bildirimi alacaksınız",
        "أذكار الصباح": "Sabah Zikirleri",
        "سيصلك اشعار لتذكيرك بقراءة أذكار الصباح": "Sabah zikirlerini okumak için bir bildirim alacaksınız",
        "أذكار المساء": "Akşam Zikirleri",
        "سيصلك اشعار لتذكيرك بقراءة أذكار المساء": "Akşam zikirlerini okumak için bir bildirim alacaksınız",
        "قراءة صفحة من القرآن كل يوم": "Her gün bir sayfa Kuran oku",
        "سيصلك اشعار كل يوم لتذكيرك بقراءة صفحة من القرآن":
            "Her gün bir sayfa Kuran okumak için bir bildirim alacaksınız",
        "قراءة سورة الكهف": "Kehif Süresi Okuma",
        "سيصلك اشعار لتذكيرك بقراءة سورة الكهف يوم الجمعة":
            "Cuma günü Kehif süresi okumak için bir bildirim alacaksınız",
        "صيام الاثنين": "Pazartesi Orucu",
        "قم بالتفعيل ليصلك اشعار لتذكيرك بالصوم يومي الاثنين والخميس":
            "Pazartesi ve Perşembe günleri oruç tutmak için bir bildirim almak için etkinleştirin",
        "صيام الخميس": "Perşembe Orucu",
        "قم بالتفعيل ليصلك اشعار لتذكيرك بالصوم":
            "Perşembe günleri oruç tutmak için bir bildirim almak için etkinleştirin",
        "صيام الايام البيض": "Aşure Orucu",
        "حديث رسول الله ﷺ": "Peygamber Efendimiz'in Hadisi",
        "سيصلك اشعار بحديث رسول الله ﷺ": "Peygamber Efendimizin hadisiyle ilgili bir bildirim alacaksınız",
        "صلاة الفجر": "Sabah Namazı",
        "صلاة الظهر": "Öğle Namazı",
        "صلاة العصر": "İkindi Namazı",
        "صلاة المغرب": "Akşam Namazı",
        "صلاة العشاء": "Yatsı Namazı",
        "سيصلك اشعار قبل موعد الاذان بدقائق": "Namaz vaktinden dakikalar önce bir bildirim alacaksınız",
        "مراجعة القرآن": "Kuran'ı Gözden Geçirme",
        "اختبر حفظك للقران واختر رقم الصفحة والجزء للآية": "Kuran'ı ezberleme testi ve ayet için sayfa ve cüz seçin",
        "أسئلة بأزرار": "Düğmelerle Sorular",
        "أسئلة بقوائم": "Listelerle Sorular",
        "اختر طريقة الاجابة:": "Cevap verme yöntemini seçin:",
        "اختر جزء:": "Juz seç",
        "اختر الصفحة:": "Sayfa seç",
        "تأكيد": "Onayla",
        " خيارات ": " Seçenekler ",
        "التالي": "Sonraki",
        "نوع الاختبار:  ": "Test türü: ",
        "الايات": "Ayetler",
        "السور": "Süreler",
        "من الصفحة    ": "Sayfasından",
        "من الجزء    ": "juzdan",
        "الى الصفحة    ": "Sayfasına",
        "الى الجزء    ": "juz'a",
        "الاجابات الصحيحة:   ": "Doğru cevaplar: ",
        "الاجابات الخاطئة:  ": "Yanlış cevaplar: ",
        "المفضلة": "Favoriler",
        "الكل": "Hepsi",
        "أسماء الله": "Allah'ın İsimleri",
        "الأذكار": "Zikirler",
        "القرآن الكريم": "Kuran-ı Kerim",
        "الحديث الشريف": "Hadis-i Şerif",
        "بحث": "Arama",
        "موعد الصلاة القادمة": "Sonraki Namaz Vakti",
        "رفض": "Reddet",
        "ملاحظة للمطور": "Geliştiriciye Not",
        "الاسم :": "İsim :",
        "الملاحظة :": "Not :",
        "ارسال": "Gönder",
        "الرجاء التأكد من كتابة الاسم": "Lütfen ismi yazdığınızdan emin olun",
        "الرجاء التأكد من كتابة الملاحظة": "Lütfen notu yazdığınızdan emin olun",
        "تم ارسال الرسالة للمطور بنجاح": "Mesaj başarıyla geliştiriciye gönderildi",
        "حدث خطأ ما الرجاء المحاولة مرة اخرى": "Bir hata oluştu, lütfen tekrar deneyin",
        "العشاء": "Yatsı",
        "المغرب": "Akşam",
        "الفجر": "Sabah",
        "العصر": "İkindi",
        "الظهر": "Öğle",
        "شروق الشمس": "Güneşin doğuşu",
        "التاريخ الهجري": "Hicri Takvim",
        "التاريخ الميلادي": "Miladi Takvim",
        "تحديث": "Güncelleme",
        "اوقات الصلاة": "Namaz Vakitleri",
        "الجُزْءُ": "Cüz",
        "سورة ": "Sûre",
        "إبحث عن آية او سورة...": "Ayet veya Sûre ara...",
        "تعديل نوع الخط": "Yazı Tipini",
        "حجم الخط": "Yazı Boyutu",
        "تغير الثيم": "Tema Değiştir",
        "اضافة علامة": "İşaretle",
        "لا محدود": "Sınırsız",
        "الآية   :  ": "Ayet   :  ",
        "المقطع :  ": "Cüz   :  ",
        "تكرار التلاوة:  ": "Tekrar Sayısı:  ",
        "اختر الآية:  ": "Ayet Seç:",
        "من الآية:": "Ayetten:",
        "الى الآية:": "Ayet'e:",
        "تحديد المقطع:": "Cüz Seç:",
        "القارئ:": "Okuyucu:",
        "اعدادات القراءة": "Okuma Ayarları",
        "الصفحة": "Sayfa",
        "قم باختيار نوع الخط المناسب لك": "Yazı Tipini Seç",
        "الرئيسية": "Ana Sayfa",
        "أسماء الله الحسنى": "Allah'ın İsimleri",
        "أذكار المسلم": "Müslümanın Zikirleri",
        "مختلف الأذكار": "Çeşitli Zikirler",
        "تعرّف على اسماء الله الحسنى": "Allah'ın İsimlerini Öğren",
        "الآية ": "Ayet",
        "حدث خطأ أثناء تشغيل الصوت": "Ses oynatılırken bir hata oluştu",
        "تم تحيل الآية بنجاح": "Ayet başarıyla işaretlendi",
        "مشكلة في الاتصال بالانترنت": "İnternet bağlantısında bir sorun oluştu",
        "لا يوجد اتصال بالانترنت": "İnternet bağlantısı yok",
        "جاري تحميل الآية": "Ayet yükleniyor",
        "حديث عن رسول الله ﷺ": "Peygamber Efendimiz ﷺ hakkında Hadis",
        "زاد المؤمن": "Zad Al-Mu'min",
        "تم نسخ النص بنجاح": "Metin başarıyla kopyalandı",
        "أذكار المنزل": "Ev Zikirleri",
        "أذكار الاستيقاظ": "Uyandığında Okunacak Dualar",
        'أذكار النوم': "Yatarken Okunacak Dualar",
        'أذكار السفر': "Yolculuk Duası",
        'أذكار الطعام': "Yemek Duası",
        'أذكار المسجد': "Mescide Giriş Duası",
        'أذكار الخلاء': "Tuvalet Duası",
        'أذكار الحج': "Hac Duası",
        "الكل >>>  ": "Hepsi >>>  ",
        " الصفحة ": "Sayfa",
        " الجزء ": "Cüz",
        "تم": "Tamam",
        "بلّغو عني ولوآية": "Bana bir ayet bildirin",
        "آية من القرآن الكريم": "Kur'an-ı Kerim'den bir ayet",
        "الجزء": "Cüz",
        "اقسام البرنامج": "Uygulama Bölümleri",
        "تم حذف النص من المفضلة": "Metin favorilerden kaldırıldı",
        "تم إضافة النص إلى المفضلة": "Metin favorilere eklendi",
        "الصفحات": "Sayfalar",
        "تم ازالة العلامة": "İşaret kaldırıldı",
        "تم اضافة العلامة": "İşaret eklendi",
        "الغاء": "İptal",
        "هل تود ازالة علامة القراءة من هذه الصفحة؟": "Bu sayfadan işareti kaldırmak istiyor musunuz?",
        "هل تود وضع علامة على هذه الصفحة؟": "Bu sayfaya işaret koymak istiyor musunuz?",
        "ازالة علامة قراءة": "İşareti Kaldır",
        "اضافة علامة قراءة": "İşaret Ekle",
        "ياسر الدوسري": "Yasser Al-Dosari",
        "ياسر السلامة": "Yasser Al-Salamah",
        "ابراهيم الدوسري": "Ibrahim Al-Dosari",
        "أيمن سويد": "Ayman Swayd",
        "الحصري": "Al-Husari",
        "المنشاوي": "Al-Menshawi",
        "عبد الباسط": "Abdul Basit",
        "العفاسي": "Al-Afasy",
        "عبد الله بصفر": "Abdullah Basfar",
        "ابو بكر الشاطري": "Abu Bakr Al-Shatri",
        "أحمد العجمي": "Ahmed Al-Ajmi",
        "هاني رفاعي": "Hani Rifai",
        "عبدالله عواد الجهني": "Abdullah Awwad Al-Juhani",
        "أحمد نعينع": "Ahmed Neana",
        "ورش - عبد الباسط": "Warsh Abdul Basit",
        "أكرم العلاقمي": "Akram Al-Aqimy",
        "فارس عباد": "Fares Abbad",
        "ماهر المعيقلي": "Maher Al-Muaqly",
        "نبيل الرفاعي": "Nabil Rifa3i",
        "ناصر القطامي": "Naser Al-Qatami",
        "سعود الشريم": "Saood Al-Shuraym",
        "محمود علي البنا": "Mahmoud Ali Al-Banna",
        "يجمع زاد المؤمن بيانات الموقع الجغرافي  لتحديد مواقيت الصلاة الخاصة بك حتى إذا كان التطبيق مغلقًا أو لم يكن قيد الاستخدام":
            "Zad Al-Mu'min, konum verilerini toplar ve namaz vakitlerinizi belirler, böylece uygulama kapalı olsa bile veya kullanımda olmasa bile",
        "تشغيل خدمات الموقع الجغرافي": "Konum hizmetlerini etkinleştir",
        "طلب الاذن بالوصول للموقع الحالي": "Mevcut konuma erişim izni iste",
        "سورة الفاتحة": "Al-Fatiha",
        "سورة البقرة": "Al-Bakara",
        "سورة ال عمران": "Al-Imran",
        "سورة النساء": "An-Nisa",
        "سورة المائـدة": "Al-Ma'ida",
        "سورة الأنعام": "Al-An'am",
        "سورة الأعراف": "Al-A'raf",
        "سورة الأنفال": "Al-Anfal",
        "سورة التوبة": "At-Tawba",
        "سورة يونس": "Yunus",
        "سورة هود": "Hud",
        "سورة يوسف": "Yusuf",
        "سورة الرعد": "Ar-Ra'd",
        "سورة إبراهيم": "Ibrahim",
        "سورة الحجر": "Al-Hijr",
        "سورة النحل": "An-Nahl",
        "سورة الإسراء": "Al-Isra",
        "سورة الكهف": "Al-Kahf",
        "سورة مريم": "Maryam",
        "سورة طه": "Ta-Ha",
        "سورة الأنبياء": "Al-Anbiya",
        "سورة الحج": "Al-Hajj",
        "سورة المؤمنون": "Al-Mu'minun",
        "سورة النور": "An-Nur",
        "سورة الفرقان": "Al-Furqan",
        "سورة الشعراء": "Ash-Shu'ara",
        "سورة النمل": "An-Naml",
        "سورة القصص": "Al-Qasas",
        "سورة العنكبوت": "Al-Ankabut",
        "سورة الروم": "Ar-Rum",
        "سورة لقمان": "Lukman",
        "سورة السجدة": "As-Sajdah",
        "سورة الأحزاب": "Al-Ahzab",
        "سورة سبأ": "Saba",
        "سورة فاطر": "Fatir",
        "سورة يس": "Ya-Sin",
        "سورة الصافات": "As-Saffat",
        "سورة ص": "Sad",
        "سورة الزمر": "Az-Zumar",
        "سورة غافر": "Ghafir",
        "سورة فصلت": "Fussilat",
        "سورة الشورى": "Ash-Shura",
        "سورة الزخرف": "Az-Zukhruf",
        "سورة الدخان": "Ad-Dukhan",
        "سورة الجاثية": "Al-Jasiye",
        "سورة الأحقاف": "Al-Ahqaf",
        "سورة محمد": "Muhammad",
        "سورة الفتح": "Al-Fath",
        "سورة الحجرات": "Al-Hujurat",
        "سورة ق": "Qaf",
        "سورة الذاريات": "Adh-Dhariyat",
        "سورة الطور": "At-Tur",
        "سورة النجم": "An-Najm",
        "سورة القمر": "Al-Qamar",
        "سورة الرحمن": "Ar-Rahman",
        "سورة الواقعة": "Al-Waqi'ah",
        "سورة الحديد": "Al-Hadid",
        "سورة المجادلة": "Al-Mujadilah",
        "سورة الحشر": "Al-Hashr",
        "سورة الممتحنة": "Al-Mumtahanah",
        "سورة الصف": "As-Saff",
        "سورة الجمعة": "Al-Jumu'ah",
        "سورة المنافقون": "Al-Munafiqun",
        "سورة التغابن": "At-Taghabun",
        "سورة الطلاق": "At-Talaq",
        "سورة التحريم": "At-Tahrim",
        "سورة الملك": "Al-Mulk",
        "سورة القلم": "Al-Qalam",
        "سورة الحاقة": "Al-Haqqah",
        "سورة المعارج": "Al-Ma'arij",
        "سورة نوح": "Nuh",
        "سورة الجن": "Al-Jinn",
        "سورة المزمل": "Al-Muzzammil",
        "سورة المدثر": "Al-Muddaththir",
        "سورة القيامة": "Al-Kıyamah",
        "سورة الإنسان": "Al-Insan",
        "سورة المرسلات": "Al-Mursalat",
        "سورة النبأ": "An-Naba",
        "سورة النازعات": "A-Naziat",
        "سورة عبس": "Abasa",
        "سورة التكوير": "At-Takwir",
        "سورة الإنفطار": "Al-Infitar",
        "سورة المطففين": "Al-Mutaffifin",
        "سورة الإنشقاق": "Al-Inshiqaq",
        "سورة البروج": "Al-Buruj",
        "سورة الطارق": "At-Tariq",
        "سورة الأعلى": "Al-A'la",
        "سورة الغاشية": "Al-Ghashiyah",
        "سورة الفجر": "Al-Fajr",
        "سورة البلد": "Al-Balad",
        "سورة الشمس": "Ash-Shams",
        "سورة الليل": "Al-Lail",
        "سورة الضحى": "Ad-Duha",
        "سورة الشرح": "Ash-Sharh",
        "سورة التين": "At-Tin",
        "سورة العلق": "Al-Alaq",
        "سورة القدر": "Al-Qadr",
        "سورة البينة": "Al-Bayyinah",
        "سورة الزلزلة": "Az-Zalzalah",
        "سورة العاديات": "Al-Adiyat",
        "سورة القارعة": "Al-Qari'ah",
        "سورة التكاثر": "At-Takathur",
        "سورة العصر": "Al-Asr",
        "سورة الهمزة": "Al-Humazah",
        "سورة الفيل": "Al-Fil",
        "سورة قريش": "Quraish",
        "سورة الماعون": "Al-Ma'un",
        "سورة الكوثر": "Al-Kauthar",
        "سورة الكافرون": "Al-Kafirun",
        "سورة النصر": "An-Nasr",
        "سورة المسد": "Al-Masad",
        "سورة الإخلاص": "Al-Ikhlas",
        "سورة الفلق": "Al-Falaq",
        "سورة الناس": "An-Nas",
        "لم يتم تحميل الآية بنجاح": "Ayet doğru bir şekilde yüklenmedi",
        "إالغاء": "İptal",
        "ثابت": "Sabit",
        "مدرّج": "Dereceli",
        "يدوي": "Manuel",
        "انقر هنا لاختيار لون التطبيق": "Uygulama rengini seçmek için buraya tıklayın",
        "تغيير لون التطبيق": "Uygulama rengini değiştir",
        "العثماني": "Osmanlıca",
        "العثماني 2": "Osmanlıca 2",
        "الكوفي": "Kufi",
        "النسخ": "Nesih",
        "العربي": "Alarabi",
        "المدينة": "Almadina",
        "نور هيرا": "Nur Hira",
        "شهرزاد": "Şehrazat",
        "ملاحظات المستخدمين": "Kullanıcı notları",
        "تم تحديث وقت الاشعار": "Bildirim zamanı güncellendi",
        "اذان العشاء": "Akşam ezanı",
        "تبقى القليل لموعد اذان العشاء": "Akşam ezanına az kaldı",
        "تم تفعيل تذكير اذان العشاء": "Akşam ezanı hatırlatıcısı etkinleştirildi",
        "سيصلك اشعار لتذكيرك باذان العشاء": "Akşam ezanı hatırlatıcısı için bildirim alacaksınız",
        "تم تعطيل الاشعار الخاص بالعشاء": "Akşam ezanı hatırlatıcısı devre dışı bırakıldı",
        "لن يصلك اشعار اذان العشاء": "Akşam ezanı hatırlatıcısı için bildirim almayacaksınız",
        "اذان  لمغرب": "Akşam ezanı",
        "تبقى القليل لموعد اذان المغرب": "Akşam ezanına az kaldı",
        "تم تفعيل تذكير اذان المغرب": "Akşam ezanı hatırlatıcısı etkinleştirildi",
        "سيصلك اشعار لتذكيرك باذان المغرب": "Akşam ezanı hatırlatıcısı için bildirim alacaksınız",
        "تم تعطيل الاشعار ": "bildirim devre dışı bırakıldı",
        "لن يصلك اشعار اذان المغرب": "Akşam ezanı hatırlatıcısı için bildirim almayacaksınız",
        "اذان العصر": "İkindi ezanı",
        "تبقى القليل لموعد اذان العصر": "İkindi ezanına az kaldı",
        "تم تفعيل تذكير اذان العصر": "İkindi ezanı hatırlatıcısı etkinleştirildi",
        "سيصلك اشعار لتذكيرك باذان العصر": "İkindi ezanı hatırlatıcısı için bildirim alacaksınız",
        "لن يصلك اشعار اذان العصر": "İkindi ezanı hatırlatıcısı için bildirim almayacaksınız",
        "اذان الظهر": "Öğle ezanı",
        "تبقى القليل لموعد اذان الظهر": "Öğle ezanına az kaldı",
        "تم تفعيل تذكير اذان الظهر": "Öğle ezanı hatırlatıcısı etkinleştirildi",
        "سيصلك اشعار لتذكيرك باذان الظهر": "Öğle ezanı hatırlatıcısı için bildirim alacaksınız",
        "لن يصلك اشعار اذان الظهر": "Öğle ezanı hatırlatıcısı için bildirim almayacaksınız",
        "تبقى القليل لموعد شروق الشمس": "Güneşin doğuşuna az kaldı",
        "تم تفعيل تذكير شروق الشمس": "Güneşin doğuşu hatırlatıcısı etkinleştirildi",
        "سيصلك اشعار لتذكيرك بموعد شروق الشمس": "Güneşin doğuşu hatırlatıcısı için bildirim alacaksınız",
        "لن يصلك اشعار  شروق الشمس": "Güneşin doğuşu hatırlatıcısı için bildirim almayacaksınız",
        "اذان الفجر": "Sabah ezanı",
        "تبقى القليل لموعد اذان الفجر": "Sabah ezanına az kaldı",
        "تم تفعيل تذكير اذان الفجر": "Sabah ezanı hatırlatıcısı etkinleştirildi",
        "سيصلك اشعار لتذكيرك باذان الفجر": "Sabah ezanı hatırlatıcısı için bildirim alacaksınız",
        "لن يصلك اشعار اذان الفجر": "Sabah ezanı hatırlatıcısı için bildirim almayacaksınız",
        "لا تنسى قراءة أذكار المساء ": "Akşam dualarını okumayı unutma",
        "لأذكار المساء فضل عظيم لا تفوته": "Akşam duaları büyük bir fazilettir, kaçırmayın",
        "تم تفعيل تذكير أذكار المساء": "Akşam duaları hatırlatıcısı etkinleştirildi",
        "لن يصلك اشعار أذكار المساء": "Akşam duaları hatırlatıcısı için bildirim almayacaksınız",
        "لا تنسى قراءة أذكار الصباح ": "Sabah dualarını okumayı unutma",
        "لأذكار الصباح فضل عظيم لا تفوته": "Sabah duaları büyük bir fazilettir, kaçırmayın",
        "تم تفعيل تذكير أذكار الصباح": "Sabah duaları hatırlatıcısı etkinleştirildi",
        "لن يصلك اشعار أذكار الصباج": "Sabah duaları hatırlatıcısı için bildirim almayacaksınız",
        "اذكر الله": "Allah'ı zikret",
        "تم تفعيل الذكر العشوائي": "Rastgele zikir etkinleştirildi",
        "سيصلك اشعار بأذكار مختلفة": "Farklı dualar için bildirim alacaksınız",
        "لن يصلك اشعار الذكر العشوائي": "Rastgele zikir için bildirim almayacaksınız",
        "لا تنسى صيام غدا فهو من الايام البيض ": "Yarın oruç tutmayı unutma, çünkü yarın oruç tutmak faziletlidir",
        "كان صلى الله عليه وسلم يصوم ثلاثة ايام من كل شهر هجري": "Hz. Muhammed (s.a.v.) her ayın üç günü oruç tutardı",
        "تم تفعيل تذكير صيام الايام البيض": "Aşure günü oruç tutma hatırlatıcısı etkinleştirildi",
        "سيصلك اشعار لتذكيرك بالصوم": "Oruç tutma hatırlatıcısı için bildirim alacaksınız",
        "لن يصلك اشعار صيام الايام البيض": "",
        "لا تنسى صيام غدا الخميس ": "Yarın perşembe oruç tutmayı unutma",
        "كان صلى الله عليه وسلم يصوم يومي الاثنين والخميس من كل اسبوع":
            "Hz. Muhammed (s.a.v.) her hafta pazartesi ve perşembe günleri oruç tutardı",
        "تم تفعيل تذكير صيام يوم الخميس": "Perşembe oruç tutma hatırlatıcısı etkinleştirildi",
        "سيصلك اشعار لتذكيرك بالصوم يوم الاربعاء": "Perşembe oruç tutma hatırlatıcısı için bildirim alacaksınız",
        "لن يصلك اشعار صيام يوم الخميس": "Perşembe oruç tutma hatırlatıcısı için bildirim almayacaksınız",
        "لا تنسى صيام غدا الاثنين ": "Yarın pazartesi oruç tutmayı unutma",
        "تم تفعيل تذكير صيام يوم الاثنين ": "Pazartesi oruç tutma hatırlatıcısı etkinleştirildi",
        "سيصلك اشعار لتذكيرك بالصوم يوم الاحد": "Pazartesi oruç tutma hatırlatıcısı için bildirim alacaksınız",
        "لن يصلك اشعار صيام يوم الاثنين": "Pazartesi oruç tutma hatırlatıcısı için bildirim almayacaksınız",
        "لا تنسى قراءة وردك اليومي من القرآن ": "Günlük Kur'an okumayı unutma",
        " قَالَ رَسُولُ اللَّهِ ﷺ:  ((اقْرَءُوا الْقُرْآنَ فَإِنَّهُ يَأْتِي يَوْمَ الْقِيَامَةِ شَفِيعًا لأَصْحَابِهِ))":
            "Hz. Muhammed (s.a.v.) şöyle buyurdu: 'Kur'an okuyun, çünkü o kıyamet günü sahipleri için şefaatçi olur'",
        "تم تفعيل تذكير قراءة الورد اليومي للقران": "Günlük Kur'an okuma hatırlatıcısı etkinleştirildi",
        "سيصلك اشعار لتذكيرك بقراءة وردك اليومي من القرآن الكريم":
            "Günlük Kur'an okuma hatırlatıcısı için bildirim alacaksınız",
        "لن يصلك اشعار قراءة الورد اليومي للقران": "Günlük Kur'an okuma hatırlatıcısı için bildirim almayacaksınız",
        "لا تنسى قراءة سورة الكهف ": "Kehf suresini okumayı unutma",
        " قَالَ رَسُولُ اللَّهِ ﷺ:  ((مَن قَرَأَ سورةَ الكَهفِ يومَ الجُمُعةِ أضاءَ له من النورِ ما بَينَ الجُمُعتينِ  ))":
            "kehif süresi k-okumak çok sevaplı",
        "تم تفعيل تذكير قراءة سورة الكهف": "Kehf suresi okuma hatırlatıcısı etkinleştirildi",
        "سيصلك اشعار لتذكيرك بقراءة سورة الكهف": "Kehf suresi okuma hatırlatıcısı için bildirim alacaksınız",
        "لن يصلك اشعار قراءة سورة الكهف": "Kehf suresi okuma hatırlatıcısı için bildirim almayacaksınız",
        "سيصلك اشعار بحديث عن رسول الله": "Hz. Muhammed (s.a.v.)'den hadis hatırlatıcısı için bildirim alacaksınız",
        "تم تفعيل تذكير حديث عن رسول الله": "Hz. Muhammed (s.a.v.)'den hadis hatırlatıcısı etkinleştirildi",
        "لن يصلك اشعار حديث عن رسول الله": "Hz. Muhammed (s.a.v.)'den hadis hatırlatıcısı için bildirim almayacaksınız",
        //--------------------------------------------------------------------------------
        "اللَّهُ": "Allah",
        "وهو الاسم الأعظم الذي تفرد به الحق سبحانه وخص به نفسه وجعله أول أسمائه، وأضافها كلها إليه فهو علم على ذاته سبحانه":
            "O, Allah'tır. O, en büyük isimdir. O, Allah, kendisini özel kıldı ve kendisine özgü kıldı ve onu ilk isim olarak kıldı ve onu tüm isimlerle birlikte kıldı. O, kendi zatı üzerinde bilgili ve yücedir",
        "الرَّحْمَنُ": "Rahman",
        "كثير الرحمة وهو اسم مقصور على الله عز وجل ولا يجوز أن يقال رحمن لغير الله، وذلك لأن رحمته وسعت كل شيء وهو أرحم الراحمين":
            "Çok merhametli olan, rahmeti geniş o",
        "الرَّحِيمُ": "Rahim",
        "هو المنعم أبدا، المتفضل دوما، فرحمته لا تنتهي":
            "O, sonsuza kadar nimet veren, daima üstün olan, rahmeti bitmeyen",
        "المَلِكُ": "Mâlik",
        "هو الله، ملك الملوك، له الملك، وهو مالك يوم الدين، ومليك الخلق فهو المالك المطلق":
            "O, Allah'tır, kralların kralı, mülk O'nundur, o, mülkün sahibidir, o, yaratıkların kralıdır, o, mutlak sahibidir",
        "بسم الله الرحمن الرحيم\n1- باب الإخلاص وإحضار النية في جميع الأعمال والأقوال والأحوال البارزة والخفية، قَالَ اللهُ تَعَالَى: {وَمَا أُمِرُوا إِلاَّ لِيَعْبُدُوا اللَّهَ مُخْلِصِينَ لَهُ الدِّينَ حُنَفَاءَ وَيُقِيمُوا الصَّلاةَ وَيُؤْتُوا الزَّكَاةَ وَذَلِكَ دِينُ الْقَيِّمَةِ} [البينة : 5]، وَقالَ تَعَالَى: {لَنْ يَنَالَ اللَّهَ لُحُومُهَا وَلا دِمَاؤُهَا وَلَكِنْ يَنَالُهُ التَّقْوَى مِنْكُمْ} [الحج: 37]، وَقالَ تَعَالَى: {قُلْ إِنْ تُخْفُوا مَا فِي صُدُورِكُمْ أَوْ تُبْدُوهُ يَعْلَمْهُ اللَّهُ} [آل عمران: 29].":
            "Ameller niyetlere göredir. Herkesin niyet ettiği şey vardır. Kim Allah ve Resûlü için hicret ederse, onun hicreti Allah ve Resûlü içindir. Kim de bir dünya malı veya bir kadın elde etmek için hicret ederse, onun hicreti de oraya yöneliktir.",
        "(إنّمَا الأَعْمَالُ بالنِّيّاتِ، وَإِنَّمَا لِكُلِّ امرِىءٍ مَا نَوَى، فَمَنْ كَانَتْ هجرته إلى الله ورسوله، فهجرته إلى الله ورسوله، ومن كانت هِجْرَتُهُ لِدُنْيَا يُصيبُهَا، أَوْ امْرَأَةٍ يَنْكَحُهَا، فَهِجْرَتُهُ إِلى مَا هَاجَرَ إِلَيْه). مُتَّفَقٌ عَلَى صِحَّتِهِ. رَوَاهُ إمَامَا الْمُحَدّثِينَ، أبُو عَبْدِ الله مُحَمَّدُ بْنُ إسْمَاعيلَ بْن إبراهِيمَ بْن المُغيرَةِ بنِ بَرْدِزْبهْ الجُعْفِيُّ البُخَارِيُّ، وَأَبُو الحُسَيْنِ مُسْلمُ بْنُ الحَجَّاجِ بْنِ مُسْلمٍ الْقُشَيريُّ النَّيْسَابُورِيُّ رضي اللهُ عنهما فِي صحيحيهما اللَّذَيْنِ هما أَصَحُّ الكُتبِ المصنفةِ.":
            "Ameller niyetlere göredir. Her insanın niyet ettiği şey, ancak kendisine aittir. Kimin hicreti Allah ve Resulü'ne ise, onun hicreti Allah ve Resulü'nedir. Kimin hicreti ise dünyalık bir şey veya bir kadın içinse, onun hicreti de, niyet ettiği şeye göredir.",
        "قالَ رسول الله صلى الله عليه وسلم: (يغْزُو جَيْشٌ الْكَعْبَةَ فإِذَا كَانُوا بِبَيْدَاءَ مِنَ الأَرضِ يُخْسَفُ بِأَوَّلِهِمْ وآخِرِهِمْ). قَالَتْ: قلتُ: يَا رَسُولَ اللهِ، كَيْفَ يُخْسَفُ بأوَّلِهِمْ وَآخِرِهِمْ وَفِيهمْ أسْوَاقُهُمْ(1)، وَمَنْ لَيْسَ مِنْهُمْ ؟! قَالَ: (يُخْسَفُ بِأَوَّلِهِمْ وَآخِرِهِمْ ثُمَّ يُبْعَثُونَ عَلَى نِيّاتِهمْ) مُتَّفَقٌ عَلَيهِ. هذَا لَفْظُ الْبُخَارِيِّ .\n\n\nـــــــــــــــ\n(1) السوقة من الناس: الرعية ومن دون الملك ومن لم يكن ذا سلطان، والذكر والأنثى فيه سواء. اللسان 6/437 (سوق).":
            "(Kabe'yi) bir ordu saldıracak ve onlar yerde çöle ulaştıklarında, ilkleriyle sonları arasında yutulacaklar.Ben,Ey Allah'ın Resulü, nasıl olur da ilkleriyle sonları yutulurken, içlerinde onların pazarları olanlar ve onlardan olmayanlar da bulunur? dedim. Şöyle buyurdu: İlkleriyle sonları yutulacak, sonra niyetlerine göre yeniden diriltilecekler.Bu, Buhari'nin rivayet ettiği bir hadistir.",
        "قَالَ النبي صلى الله عليه وسلم: (لا هِجْرَةَ بَعْدَ الفَتْحِ، وَلَكِنْ جِهَادٌ وَنِيَّةٌ، وَإِذَا اسْتُنْفِرْتُمْ(1) فانْفِرُوا) مُتَّفَقٌ عَلَيْهِ.\n\n\nـــــــــــــ\n(1) الاستنفار: الاستنجاد والاستنصار: أي إذا طلب منكم النصرة فأجيبوا وانفروا خارجين إلى الإعانة. النهاية 5/95.a":
            "Hz. Peygamber (sallallahu aleyhi ve sellem) şöyle buyurdu: Fethin ardından hicret yoktur, ancak cihad ve niyet vardır. Eğer savaşa çağrılırsanız, cevap verin ve çıkın",
        "كُنَّا مَعَ النَّبيِّ صلى الله عليه وسلم في غَزَاةٍ، فَقالَ: (إِنَّ بالمدِينَةِ لَرِجَالاً ما سِرْتُمْ مَسِيراً، وَلاَ قَطَعْتُمْ وَادِياً، إلاَّ كَانُوا مَعَكمْ حَبَسَهُمُ الْمَرَضُ). وَفي روَايَة: (إلاَّ شَرَكُوكُمْ في الأجْرِ)رواهُ مسلمٌ. ورواهُ البخاريُّ عن أنسٍ رضي الله عنه قَالَ: رَجَعْنَا مِنْ غَزْوَةِ تَبُوكَ مَعَ النَّبيِّ صلى الله عليه وسلم فقال : (إنَّ أقْواماً خَلْفَنَا بالْمَدِينَةِ مَا سَلَكْنَا شِعْباً (1)، وَلاَ وَادياً، إلاّ وَهُمْ مَعَنَا؛ حَبَسَهُمُ العُذْرُ).\n\nـــــــــــــ\n(1) الشِّعب: ما انفرج بين جبلين. اللسان 7/126 (شعب).":
            "Biz, Peygamber Efendimiz (sallallahu aleyhi ve sellem) ile bir gazvede bulunuyorduk. O şöyle buyurdu: (İnna bil-medine leriâce menn sirtum mesîren, ve lâ kate'tum vâdiyâ, illâ kânû maakum habsahumu'l-mereż). Ve başka bir rivayette şöyle buyurdu: (İllâ şerrekum fi'l-ecri). Müslim tarafından rivayet edilmiştir.",
        "كَانَ أبي يَزيدُ أخْرَجَ دَنَانِيرَ يَتَصَدَّقُ بِهَا، فَوَضعَهَا عِنْدَ رَجُلٍ في الْمَسْجِدِ، فَجِئْتُ فأَخذْتُها فَأَتَيْتُهُ بِهَا. فقالَ: واللهِ، مَا إيَّاكَ أرَدْتُ، فَخَاصَمْتُهُ إِلى رسولِ اللهِ صلى الله عليه وسلم، فقَالَ: (لكَ مَا نَوَيْتَ يَا يزيدُ، ولَكَ ما أخَذْتَ يَا مَعْنُ). رواهُ البخاريُّ.":
            "Benim babam, bir miktar dinarları sadaka olarak vermek üzere çıkardı ve onları camide bir adamın yanına koydu. Ben geldim ve onları aldım, sonra onun yanına gittim ve ona verdim. O dedi ki: 'Yemin olsun, seninle bir anlaşma yapmadım.' Bunun üzerine onunla birlikte Peygamber Efendimiz (sallallahu aleyhi ve sellem)'in huzuruna gittim. Peygamber Efendimiz şöyle buyurdu: '(Ey Yezid), niyet ettiğin senindir ve aldığın da senindir, ey Ma'n (adamı)!' Buhari tarafından rivayet edilmiştir.",
        "جاءنِي رسولُ اللهِ صلى الله عليه وسلم يَعُودُنِي عَامَ حَجَّةِ الوَدَاعِ مِنْ وَجَعٍ اشْتَدَّ بي، فقُلْتُ: يَا رَسُولَ اللهِ، إنِّي قَدْ بَلَغَ بي مِنَ الوَجَعِ مَا تَرَى، وَأَنَا ذُو مالٍ وَلا يَرِثُني إلا ابْنَةٌ لي، أفأَتَصَدَّقُ بِثُلُثَيْ مَالِي؟ قَالَ: (لا)، قُلْتُ: فالشَّطْرُ يَا رَسُولَ اللهِ؟ فقَالَ: (لا)، قُلْتُ: فالثُّلُثُ يَا رَسُولَ اللهِ؟ قَالَ: (الثُّلُثُ والثُّلُثُ كَثيرٌ - أَوْ كبيرٌ - إنَّكَ إنْ تَذَرْ وَرَثَتَكَ أغنِيَاءَ خيرٌ مِنْ أنْ تَذَرَهُمْ عَالَةً (1)، يتكفَّفُونَ النَّاسَ، وَإنَّكَ لَنْ تُنفِقَ نَفَقَةً تَبْتَغي بِهَا وَجهَ اللهِ إلاَّ أُجِرْتَ عَلَيْهَا حَتَّى مَا تَجْعَلُ في فِيِّ امْرَأَتِكَ)، قَالَ: فَقُلتُ: يَا رسولَ اللهِ، أُخلَّفُ (2)، بعدَ أصْحَابي؟ قَالَ: (إِنَّكَ لَنْ تُخَلَّفَ فَتَعملَ عَمَلاً تَبتَغي بِهِ وَجْهَ اللهِ إلاَّ ازْدَدتَ بِهِ دَرَجةً ورِفعَةً، وَلَعلَّكَ أنْ تُخَلَّفَ حَتّى يَنتَفِعَ بِكَ أقْوَامٌ وَيُضَرَّ بِكَ آخرونَ. اللَّهُمَّ أَمْضِ لأصْحَابي هِجْرَتَهُمْ ولاَ تَرُدَّهُمْ عَلَى أعقَابهمْ، لكنِ البَائِسُ سَعدُ بْنُ خَوْلَةَ) يَرْثي لَهُ رَسُولُ اللهِ صلى الله عليه وسلم أنْ ماتَ بمَكَّة. مُتَّفَقٌ عليهِ .\n\nـــــــــــــ\n(1)  جمع عائل، وهو الفقير. النهاية 3/323 .\n(2) التخلف: التأخر. النهاية 2/67 ":
            "Resûlullah (sallallahu aleyhi ve sellem) beni, Veda Haccı'nda bana uğrayarak ziyaret ettiğinde, beni şiddetli bir sıkıntı sarıyordu. Dedim ki: 'Ey Allah'ın Resûlü, benim sıkıntımdan haberdar oldun, bana gelene kadar yaşadığım acıları sen göremedin. Ben maddi varlığa sahibim ve beni sadece bir kızım miras alacak. Acaba malımın üçte ikisini sadaka olarak verebilir miyim?' Resûlullah şöyle cevap verdi: 'Hayır.' Dedim ki: 'Öyleyse yarısını, ey Allah'ın Resûlü?' O şöyle buyurdu: 'Hayır.' Dedim ki: 'Peki, üçte birini, ey Allah'ın Resûlü?' O şöyle cevap verdi: 'Üçte bir ve üçte bir çok fazladır - veya büyüktür -. Şüphesiz, sen varislerine zenginlik bırakmak, onları muhtaç duruma düşürmekten daha hayırlıdır. Onlar insanlardan sadaka istemezler. Ve şüphesiz, sen Allah'ın yüzünü aramak için harcama yapmazsan, o harcamayı yapman üzerine sen mükâfatlandırılırsın, hatta eşinin içinde bırakacağın yiyecekle bile. Dedim ki: 'Ey Allah'ın Resûlü, benden sonra sahabilerimden geri kalacak mıyım?' O şöyle buyurdu: 'Sen geri kalmayacaksın, öyle ki Allah'ın yüzünü aramak için bir amel yaparsan, onunla derecen yükselir ve yücelirsin. Belki geri kalırsın da insanlar sana fayda sağlar, diğerleri ise sana zarar verir. Allah'ım, sahabilerimin hicretlerini tamamla ve onları geri döndürme, ancak Sa'd bin Huveylid (daha sonra Mekke'de öldü) gibi bahtsız olan birini geride bırak.' Müslim ve Buhari'nin mutabık olduğu hadistir.",
        "قَالَ رَسُولُ الله صلى الله عليه وسلم : (إنَّ الله لا ينْظُرُ إِلى أجْسَامِكُمْ، ولا إِلى صُوَرِكمْ، وَلَكن ينْظُرُ إلى قُلُوبِكمْ وأعمالكم) رواه مسلم.":
            "Resûlullah (sallallahu aleyhi ve sellem) şöyle buyurdu: 'Şüphesiz ki Allah, bedenlerinize veya suretlerinize bakmaz, ancak kalplerinize ve amellerinize bakar.' Müslim tarafından rivayet edilmiştir.",
        " سُئِلَ رسولُ الله صلى الله عليه وسلم عَنِ الرَّجُلِ يُقاتلُ شَجَاعَةً، ويُقَاتِلُ حَمِيَّةً، ويُقَاتِلُ رِيَاءً، أَيُّ ذلِكَ في سبيلِ الله؟ فقال رَسُول الله aصلى الله عليه وسلم: (مَنْ قَاتَلَ لِتَكونَ كَلِمَةُ اللهِ هي العُلْيَا، فَهوَ في سبيلِ اللهِ) مُتَّفَقٌ عَلَيهِ.":
            "Resûlullah (sallallahu aleyhi ve sellem)'e, kişinin cesaretle, kahramanlıkla ve gösterişsiz bir şekilde savaşmasının Allah yolunda olup olmadığı soruldu. Resûlullah (sallallahu aleyhi ve sellem) şöyle cevap verdi: 'Allah'ın kelimesi yüceltilsin diye savaşan kimse, Allah'ın yolundadır.' Bu hadis, Müslim tarafından rivayet edilmiştir.",
        "أَنَّ النَّبيَّ صلى الله عليه وسلم قَالَ: (إِذَا التَقَى المُسلِمَان بسَيْفَيهِمَا فالقَاتِلُ وَالمَقْتُولُ في النّارِ) قُلتُ: يا رَسُولَ اللهِ، هذا القَاتِلُ فَمَا بَالُ المقْتُولِ؟ قَالَ: (إنَّهُ كَانَ حَريصاً عَلَى قتلِ صَاحِبهِ) مُتَّفَقٌ عليهِ.":
            "Resûlullah (sallallahu aleyhi ve sellem) şöyle buyurdu: 'İki Müslüman, kılıçlarıyla karşılaştıklarında, öldüren ve öldürülen cehennemdedir.' Ben dedim ki: 'Ya Resûlullah, öldürenin durumu ne olur?' Resûlullah (sallallahu aleyhi ve sellem) şöyle cevap verdi: 'O, arkadaşını öldürmeye kararlıydı.' Bu hadis, Müslim ve Buhari tarafından rivayet edilmiştir.",
        "قالَ رَسُول الله صلى الله عليه وسلم: (صَلاةُ الرَّجلِ في جمَاعَةٍ تَزيدُ عَلَى صَلاتهِ في سُوقِهِ وبيتهِ بضْعاً (1)، وعِشرِينَ دَرَجَةً، وَذَلِكَ أنَّ أَحدَهُمْ إِذَا تَوَضَّأَ فَأَحْسَنَ الوُضوءَ، ثُمَّ أَتَى المَسْجِدَ لا يُرِيدُ إلاَّ الصَّلاةَ، لاَ يَنْهَزُهُ إِلاَّ الصَلاةُ: لَمْ يَخْطُ خُطْوَةً إِلاَّ رُفِعَ لَهُ بِهَا دَرجَةٌ، وَحُطَّ عَنْهُ بها خَطِيئَةٌ حَتَّى يَدْخُلَ المَسْجِدَ، فإِذا دَخَلَ المَسْجِدَ كَانَ في الصَّلاةِ مَا كَانَتِ الصَّلاةُ هِي تَحْبِسُهُ، وَالمَلائِكَةُ يُصَلُّونَ عَلَى أَحَدِكُمْ مَا دَامَ في مَجْلِسِهِ الَّذِي صَلَّى فِيهِ، يَقُولُونَ: اللَّهُمَّ ارْحَمْهُ، اللَّهُمَّ اغْفِرْ لَهُ، اللَّهُمَّ تُبْ عَلَيهِ، مَا لَم يُؤْذِ فيه، مَا لَمْ يُحْدِثْ فِيهِ). مُتَّفَقٌ عليه، وهذا لفظ مسلم.\nوقوله صلى الله عليه وسلم: (يَنْهَزُهُ) هُوَ بِفَتْحِ اليَاءِ والْهَاءِ وبالزَّايِ: أَيْ يُخْرِجُهُ ويُنْهضُهُ.\n\nـــــــــــــ\n(1)  البضع: في العدد بالكسر، وقد يفتح ما بين الثلاث إلى التسع. وقيل: ما بين الواحد إلى العشرة، لأنه قطعة من العدد. النهاية 1/132 .":
            "Resûlullah (sallallahu aleyhi ve sellem) şöyle buyurdu: 'Bir kişinin cemaatle kıldığı namaz, pazarında veya evinde kıldığı namazından daha üstündür ve ona yirmi derece ilave eder. Çünkü bir kişi, güzel bir şekilde abdest alıp sonra sadece namaz için camiye gelir ve namaz dışında bir şey arzulamaz. İçeriye adım atmadan önce her adımıyla bir derece yükseltilir ve her adımıyla bir günahı affedilir. Camiye girdiğinde, namazın onu içinde hapsettiği kadar namazda kalır. Melekler de bir kişi namazını kıldığı mecliste bulundukları sürece onun için şöyle derler: 'Allah'ım, ona rahmet eyle, Allah'ım, onun günahlarını bağışla, Allah'ım, ona tevbe nasip eyle, ta ki o mecliste zarar vermediği ve orada bir hata işlemediği sürece.' Bu hadis, Müslim tarafından rivayet edilmiştir.",
        "عن رَسُول الله صلى الله عليه وسلم، فيما يروي عن ربهِ، تباركَ وتعالى، قَالَ: (إنَّ اللهَ كَتَبَ الحَسَنَاتِ والسَّيِّئَاتِ ثُمَّ بَيَّنَ ذلِكَ، فَمَنْ هَمَّ (1)، بحَسَنَةٍ فَلَمْ يَعْمَلْهَا كَتَبَها اللهُ تَبَارَكَ وتَعَالى عِنْدَهُ حَسَنَةً كامِلَةً، وَإنْ هَمَّ بهَا فَعَمِلَهَا كَتَبَهَا اللهُ عَشْرَ حَسَناتٍ إِلى سَبْعمئةِ ضِعْفٍ إِلى أَضعَافٍ كَثيرةٍ، وإنْ هَمَّ بِسَيِّئَةٍ فَلَمْ يَعْمَلْهَا كَتَبَهَا اللهُ تَعَالَى عِنْدَهُ حَسَنَةً كَامِلةً، وَإنْ هَمَّ بِهَا فَعَمِلَهَا كَتَبَهَا اللهُ سَيِّئَةً وَاحِدَةً) مُتَّفَقٌ عليهِ.\n\nـــــــــــــ\n(1) همّ بالأمر يهمّ، إذا عزم عليه. النهاية 5/274 .":
            "Rasulullah sallallahu aleyhi ve sellem, Rabbinden nakledilen bir hadiste şöyle buyurdu: 'Allah, hasenatı ve seyyiatı yazdıktan sonra bunu açıkladı. Kim bir hasenat niyet ederse ancak onu işlemezse, Allah onu kendi nezdinde tam bir hasenat olarak yazar. Kim de niyet ettiği hasenatı işlerse, Allah onu on hasenattan yedi yüz katına kadar artırır. Kim bir seyyiat niyet ederse ancak onu işlemezse, Allah onu kendi nezdinde tam bir hasenat olarak yazar. Kim de niyet ettiği seyyiati işlerse, Allah onu tek bir seyyiat olarak yazar.' Mütefekkirdir (Buhari ve Müslim)",
        "(انطَلَقَ ثَلاثَةُ نَفَرٍ (1)، مِمَّنْ كَانَ قَبْلَكُمْ حَتَّى آوَاهُمُ المَبيتُ إِلى غَارٍ فَدَخلُوهُ، فانْحَدرَتْ صَخْرَةٌ مِنَ الجَبَلِ فَسَدَّتْ عَلَيْهِمُ الغَارَ، فَقالُوا: إِنَّهُ لاَ يُنْجِيكُمْ مِنْ هذِهِ الصَّخْرَةِ إِلاَّ أنْ تَدْعُوا اللهَ بصَالِحِ أعْمَالِكُمْ. قَالَ رجلٌ مِنْهُمْ: اللَّهُمَّ كَانَ لِي أَبَوانِ شَيْخَانِ كبيرانِ، وكُنْتُ لا أغْبِقُ (2)، قَبْلَهُمَا أهْلاً ولاَ مالاً، فَنَأَى (3)، بِي طَلَب الشَّجَرِ يَوْماً فلم أَرِحْ عَلَيْهمَا حَتَّى نَامَا، فَحَلَبْتُ لَهُمَا غَبُوقَهُمَا فَوَجَدْتُهُما نَائِمَينِ، فَكَرِهْتُ أنْ أُوقِظَهُمَا وَأَنْ أغْبِقَ قَبْلَهُمَا أهْلاً أو مالاً، فَلَبَثْتُ - والْقَدَحُ عَلَى يَدِي - أنتَظِرُ اسْتِيقَاظَهُما حَتَّى بَرِقَ الفَجْرُ والصِّبْيَةُ يَتَضَاغَوْنَ (4)، عِنْدَ قَدَميَّ، فاسْتَيْقَظَا فَشَرِبا غَبُوقَهُما. اللَّهُمَّ إنْ كُنْتُ فَعَلْتُ ذلِكَ ابِتِغَاء وَجْهِكَ فَفَرِّجْ عَنّا مَا نَحْنُ فِيهِ مِنْ هذِهِ الصَّخْرَةِ، فانْفَرَجَتْ شَيْئاً لا يَسْتَطيعُونَ الخُروجَ مِنْهُ. قَالَ الآخر: اللَّهُمَّ إنَّهُ كانَتْ لِيَ ابْنَةُ عَمّ، كَانَتْ أَحَبَّ النّاسِ إليَّ - وفي رواية: كُنْتُ أُحِبُّها كأَشَدِّ مَا يُحِبُّ الرِّجَالُ النساءَ - فأَرَدْتُهَا عَلَى نَفْسِهَا (5)، فامْتَنَعَتْ منِّي حَتَّى أَلَمَّتْ بها سَنَةٌ مِنَ السِّنِينَ فَجَاءتْنِي فَأَعْطَيْتُهَا عِشْرِينَ وَمئةَ دينَارٍ عَلَى أنْ تُخَلِّيَ بَيْني وَبَيْنَ نَفْسِهَا فَفعَلَتْ، حَتَّى إِذَا قَدَرْتُ عَلَيْهَا - وفي رواية: فَلَمَّا قَعَدْتُ بَينَ رِجْلَيْهَا، قالتْ: اتَّقِ اللهَ وَلاَ تَفُضَّ الخَاتَمَ إلاّ بِحَقِّهِ (6)، فَانصَرَفْتُ عَنْهَا وَهيَ أَحَبُّ النَّاسِ إليَّ وَتَرَكْتُ الذَّهَبَ الَّذِي أعْطَيتُها. اللَّهُمَّ إنْ كُنْتُ فَعَلْتُ ذلِكَ ابْتِغاءَ وَجْهِكَ فافْرُجْ عَنَّا مَا نَحْنُ فيهِ، فانْفَرَجَتِ الصَّخْرَةُ، غَيْرَ أَنَّهُمْ لا يَسْتَطِيعُونَ الخُرُوجَ مِنْهَا. وَقَالَ الثَّالِثُ: اللَّهُمَّ اسْتَأْجَرْتُ أُجَرَاءَ وأَعْطَيْتُهُمْ أجْرَهُمْ غيرَ رَجُل واحدٍ تَرَكَ الَّذِي لَهُ وَذَهبَ، فَثمَّرْتُ أجْرَهُ حَتَّى كَثُرَتْ مِنهُ الأمْوَالُ، فَجَاءنِي بَعدَ حِينٍ، فَقالَ: يَا عبدَ اللهِ، أَدِّ إِلَيَّ أجْرِي، فَقُلْتُ: كُلُّ مَا تَرَى مِنْ أجْرِكَ: مِنَ الإبلِ وَالبَقَرِ والْغَنَمِ والرَّقيقِ، فقالَ: يَا عبدَ اللهِ، لاَ تَسْتَهْزِىءْ بي! فَقُلْتُ: لاَ أسْتَهْزِئ بِكَ، فَأَخَذَهُ كُلَّهُ فاسْتَاقَهُ فَلَمْ يتْرُكْ مِنهُ شَيئاً. الَّلهُمَّ إنْ كُنتُ فَعَلْتُ ذلِكَ ابِتِغَاءَ وَجْهِكَ فافْرُجْ عَنَّا مَا نَحنُ فِيهِ، فانْفَرَجَتِ الصَّخْرَةُ فَخَرَجُوا يَمْشُونَ) (7)، مُتَّفَقٌ عليهِ .\n\nـــــــــــــ\n(1) نفر: هو اسم جمع، يقع على جماعة الرجال خاصة ما بين الثلاثة إلى العشرة، ولا واحد له من لفظه. النهاية 5/93 .\n(2) لا أغبق: أي ما كنت أقدم عليهما أحداً في شرب نصيبهما من اللبن الذي يشربانه. والغبوق شرب آخر النهار مقابل الصبوح. النهاية 3/341 .\n(3) نأى: بَعُد.\n(4) أي: يتصايحون ويبكون.\n(5) كناية عن الجماع .\n(6) الفض: الكسر والفتح، والخاتم كناية عن الفرج وعذرة البكارة، وحقه التزويج المشروع. دليل الفالحين 1/84.\n(7) في الحديث: استحباب الدعاء حال الكرب والتوسل بصالح العمل، وفيه فضيلة بر الوالدين وفضل خدمتهما وإيثارهما على من سواهما، وفيه فضل العفاف، وفيه فضل حسن العهد وأداء الأمانة والسماحة في المعاملة وإثبات كرامات الأولياء وهو مذهب أهل الحق. انظر: دليل الفالحين 1/86 .\n":
            "Üç kişi yola çıktılar (1), sizden önceki insanlardan. Gecenin bir vaktinde bir mağaraya sığındılar ve mağaraya bir kayanın düşmesi sonucu mağara kapandı. Dışarı çıkabilmeleri için sadece Allah'a salih amellerinizi dua etmeniz gerektiğini söylediler. Onlardan biri şöyle dedi: Ey Allahım, benim yaşlı iki dedem vardı ve onlardan önce ne mal ne de ailem vardı. Bir gün ağaç toplamaya gittim ve onlar uyuyana kadar yanlarında bekledim. Uyanmalarını beklerken onları uyandırmak ve kendimden önce ailem ve malım olması beni rahatsız etti. Sonunda sabaha kadar bekledim ve onlar uyandığında su içtiler. Ey Allahım, eğer bunu senin rızanı kazanmak için yaptıysam, bizi bu kayadan kurtar. Kayanın bir kısmı hareket etti, ancak hala dışarı çıkamadılar. Diğeri şöyle dedi: Ey Allahım, benim kuzenim vardı ve onu herkesten daha çok seviyordum - diğer bir rivayette, erkeklerin kadınları sevdiği kadar seviyordum. Kendisi üzerine bir hak olduğunda onu bana vermeyi istedim, ama o benden uzaklaştı ve bir yıl boyunca benimle konuşmadı. Sonunda bana geldi ve ona 1200 dinar verdim, ancak benimle aramda bir anlaşma yapmasını istedim. Bunu yaptı ve o zaman o kayadan kurtuldular, ancak hala dışarı çıkamadılar.Üçüncüsü şöyle dedi: Ey Allahım, ben işçi kiraladım ve onlara paralarını ödedim, fakat sadece bir kişi geri dönmedi ve kayboldu. Paranın artmasıyla birlikte servetim arttı. Bir süre sonra o geldi ve Ey Abdullah, bana paramı ver dediğinde, ona, Senin mülkün: develer, sığırlar, koyunlar ve kölelerin olduğu her şeydir dedim. O ise Ey Abdullah, benimle alay etme! dedi ve tüm serveti alıp gitti. Ey Allahım, eğer bunu senin rızanı kazanmak için yaptıysam, bizi bu kayadan kurtar. Kayadan bir kısım açıldı ve çıktılar.",
      };
  Map<String, String> get en => {
        "تنشيط الوضع اليلي": "Activate Dark Mode",
        "الإعدادات": "Settings",
        "انقر هنا لاختيار الوضع اليلي": "Click here to select dark mode",
        "تشفيل صوت الاشعارات": "Enable Notification Sound",
        "عند تفعيل هذا الخيار سيتم تشفيل صوت الاشعارات":
            "When you activate this option, the notification sound will be turned on",
        "لغة البرنامج": "App Language",
        "قم بإختيار لغة البرنامج المناسبة لك": "Choose the appropriate app language for you",
        "عالي  20 قأكثر يوميا": "High 20 or more daily",
        "متوسط  11-19  يوميا": "Medium 11-19 daily",
        "منخفض  5-10  يوميا": "Low 5-10 daily",
        "نادر  1-5  يوميا": "Rare 1-5 daily",
        "غير مسموح": "Not Allowed",
        "لا يمكنك تغيير الاشعارات الخاصة بهذه الصلاة": "You cannot change the notifications for this prayer",
        "حسنا": "Okay",
        "المنبه": "Alarm",
        "تذكير الاحاديث": "Hadith Reminder",
        "الأذكار اليومية": "Daily Remembrance",
        "قراءة القرآن": "Read Quran",
        "اوقات الصيام": "Fasting Times",
        "اوقات الاذان": "Prayer Times",
        "أذكار عشوائية": "Random Remembrance",
        "سيصلك اشعار بذكر عشوائي": "You will receive a random remembrance notification",
        "أذكار الصباح": "Morning Remembrance",
        "سيصلك اشعار لتذكيرك بقراءة أذكار الصباح":
            "You will receive a notification to remind you to read the morning remembrance",
        "أذكار المساء": "Evening Remembrance",
        "سيصلك اشعار لتذكيرك بقراءة أذكار المساء":
            "You will receive a notification to remind you to read the evening remembrance",
        "قراءة صفحة من القرآن كل يوم": "Read a page of the Quran every day",
        "سيصلك اشعار كل يوم لتذكيرك بقراءة صفحة من القرآن":
            "You will receive a notification every day to remind you to read a page of the Quran",
        "قراءة سورة الكهف": "Read Surat Al-Kahf",
        "سيصلك اشعار لتذكيرك بقراءة سورة الكهف يوم الجمعة":
            "You will receive a notification to remind you to read  Al-Kahf on Friday",
        "صيام الاثنين": "Monday Fasting",
        "قم بالتفعيل ليصلك اشعار لتذكيرك بالصوم يومي الاثنين والخميس":
            "Activate to receive a notification to remind you to fast on Mondays and Thursdays",
        "صيام الخميس": "Thursday Fasting",
        "قم بالتفعيل ليصلك اشعار لتذكيرك بالصوم": "Activate to receive a notification to remind you to fast",
        "صيام الايام البيض": "Ashura Fasting",
        "حديث رسول الله ﷺ": "Hadith of the Prophet Muhammad ﷺ",
        "سيصلك اشعار بحديث رسول الله ﷺ": "You will receive a notification with the Hadith of the Prophet Muhammad ﷺ",
        "صلاة الفجر": "Fajr Prayer",
        "صلاة الظهر": "Dhuhr Prayer",
        "صلاة العصر": "Asr Prayer",
        "صلاة المغرب": "Maghrib Prayer",
        "صلاة العشاء": "Isha Prayer",
        "سيصلك اشعار قبل موعد الاذان بدقائق": "You will receive a notification minutes before the prayer time",
        "مراجعة القرآن": "Quran Review",
        "اختبر حفظك للقران واختر رقم الصفحة والجزء للآية":
            "Test your memorization of the Quran and choose the page number and part of the verse",
        "أسئلة بأزرار": "Questions with Buttons",
        "أسئلة بقوائم": "Questions with Lists",
        "اختر طريقة الاجابة:": "Choose the answer method:",
        "اختر جزء:": "Choose a part:",
        "اختر الصفحة:": "Choose a page:",
        "تأكيد": "Confirm",
        " خيارات ": "Options",
        "التالي": "Next",
        "نوع الاختبار:  ": "Test Type: ",
        "الايات": "Ayahs",
        "السور": "Surahs",
        "من الصفحة    ": "From page",
        "من الجزء    ": "From part",
        "الى الصفحة    ": "To page",
        "الى الجزء    ": "To part",
        "الاجابات الصحيحة:   ": "Correct answers:",
        "الاجابات الخاطئة:  ": "Wrong answers:",
        "المفضلة": "Favorites",
        "الكل": "All",
        "أسماء الله": "Names of Allah",
        "الأذكار": "Remembrance",
        "القرآن الكريم": "Quran",
        "الحديث الشريف": "Hadith",
        "بحث": "Search",
        "موعد الصلاة القادمة": "Next Prayer Time",
        "رفض": "Reject",
        "ملاحظة للمطور": "Note to the developer",
        "الاسم :": "Name :",
        "الملاحظة :": "Note :",
        "ارسال": "Send",
        "الرجاء التأكد من كتابة الاسم": "Please make sure to write the name",
        "الرجاء التأكد من كتابة الملاحظة": "Please make sure to write the note",
        "تم ارسال الرسالة للمطور بنجاح": "The message has been sent to the developer successfully",
        "حدث خطأ ما الرجاء المحاولة مرة اخرى": "An error occurred, please try again",
        "العشاء": "Isha",
        "المغرب": "Maghrib",
        "الفجر": "Fajr",
        "العصر": "Asr",
        "الظهر": "Dhuhr",
        "شروق الشمس": "Sunrise",
        "التاريخ الهجري": "Hijri Date",
        "التاريخ الميلادي": "Gregorian Date",
        "تحديث": "Refresh",
        "اوقات الصلاة": "Prayer Times",
        "الجُزْءُ": "Part",
        "سورة ": "Surah",
        "إبحث عن آية او سورة...": "Search for an Ayah or Surah...",
        "تعديل نوع الخط": "Font Type",
        "حجم الخط": "Font Size",
        "تغير الثيم": "Change Theme",
        "اضافة علامة": "Add Bookmark",
        "لا محدود": "Unlimited",
        "الآية   :  ": "Ayah   :  ",
        "المقطع :  ": "Part   :  ",
        "تكرار التلاوة:  ": "Recitation Repeat:  ",
        "اختر الآية:  ": "Choose Ayah:  ",
        "من الآية:": "From Ayah:",
        "الى الآية:": "To Ayah:",
        "تحديد المقطع:": "Choose Part:",
        "القارئ:": "Reader:",
        "اعدادات القراءة": "Recitation Settings",
        "الصفحة": "Page",
        "قم باختيار نوع الخط المناسب لك": "Choose the font type that suits you",
        "الرئيسية": "Home",
        "أسماء الله الحسنى": "Names of Allah",
        "أذكار المسلم": "Muslim Remembrance",
        "مختلف الأذكار": "Various Remembrance",
        "تعرّف على اسماء الله الحسنى": "Learn the names of Allah",
        "الآية ": "Ayah",
        "حدث خطأ أثناء تشغيل الصوت": "An error occurred while playing the sound",
        "تم تحيل الآية بنجاح": "The Ayah has been bookmarked successfully",
        "مشكلة في الاتصال بالانترنت": "Problem connecting to the Internet",
        "لا يوجد اتصال بالانترنت": "No Internet connection",
        "جاري تحميل الآية": "Loading Ayah",
        "حديث عن رسول الله ﷺ": "Hadith about the Messenger of Allah ﷺ",
        "زاد المؤمن": "Zad Al-Mu'min",
        "تم نسخ النص بنجاح": "The text has been copied successfully",
        "أذكار المنزل": "Home Remembrance",
        "أذكار الاستيقاظ": "Waking Up Remembrance",
        'أذكار النوم': "Sleeping Remembrance",
        'أذكار السفر': "Travel Remembrance",
        'أذكار الطعام': "Eating Remembrance",
        'أذكار المسجد': "Mosque Remembrance",
        'أذكار الخلاء': "Toilet Remembrance",
        'أذكار الحج': "Hajj Remembrance",
        "الكل >>>  ": "All >>>  ",
        " الصفحة ": "Page",
        " الجزء ": "Juz",
        "تم": "Done",
        "بلّغو عني ولوآية": "Report me even with one verse",
        "آية من القرآن الكريم": "A verse from the Holy Quran",
        "الجزء": "Juz",
        "اقسام البرنامج": "Program Sections",
        "تم حذف النص من المفضلة": "The text has been removed from favorites",
        "تم إضافة النص إلى المفضلة": "The text has been added to favorites",
        "الصفحات": "Pages",
        "تم ازالة العلامة": "The bookmark has been removed",
        "تم اضافة العلامة": "The bookmark has been added",
        "الغاء": "Cancel",
        "هل تود ازالة علامة القراءة من هذه الصفحة؟": "Do you want to remove the bookmark from this page?",
        "هل تود وضع علامة على هذه الصفحة؟": "Do you want to add a bookmark to this page?",
        "ازالة علامة قراءة": "Remove Bookmark",
        "اضافة علامة قراءة": "Add Bookmark",
        "ياسر الدوسري": "Yasser Al-Dosari",
        "ياسر السلامة": "Yasser Al-Salamah",
        "ابراهيم الدوسري": "Ibrahim Al-Dosari",
        "أيمن سويد": "Ayman Sowaid",
        "الحصري": "Al-Husari",
        "المنشاوي": "Al-Minshawi",
        "عبد الباسط": "Abdul Basit",
        "العفاسي": "Al-Afasy",
        "عبد الله بصفر": "Abdullah Basfar",
        "ابو بكر الشاطري": "Abu Bakr Al-Shatri",
        "أحمد العجمي": "Ahmed Al-Ajmi",
        "هاني رفاعي": "Haney Rifai",
        "عبدالله عواد": "Abdullah Al-Johani",
        "أحمد نعينع": "Ahmed Neana",
        "ورش - عبد الباسط": "Abdul Basit-Warsh",
        "أكرم العلاقمي": "Akram Al-Alaqmi",
        "فارس عباد": "Fares Abbad",
        "ماهر المعيقلي": "Maher Al-Muaiqly",
        "نبيل الرفاعي": "Nabil Rifai",
        "ناصر القطامي": "Nasser Al-Qatami",
        "سعود الشريم": "Saood Al-Shuraym",
        "محمود علي البنا": "Ali Al-Banna",
        "يجمع زاد المؤمن بيانات الموقع الجغرافي  لتحديد مواقيت الصلاة الخاصة بك حتى إذا كان التطبيق مغلقًا أو لم يكن قيد الاستخدام":
            "Zad Al-Mu'min collects geolocation data to determine your prayer times even if the app is closed or not in use",
        "تشغيل خدمات الموقع الجغرافي": "Turn on geolocation services",
        "طلب الاذن بالوصول للموقع الحالي": "Request permission to access current location",
        "سورة الفاتحة": "Al-Fatihah",
        "سورة البقرة": "Al-Baqarah",
        "سورة ال عمران": "Al-Imran",
        "سورة النساء": "An-Nisa",
        "سورة المائـدة": "Al-Ma'idah",
        "سورة الأنعام": "Al-An'am",
        "سورة الأعراف": "Al-A'raf",
        "سورة الأنفال": "Al-Anfal",
        "سورة التوبة": "At-Tawbah",
        "سورة يونس": "Yunus",
        "سورة هود": "Hud",
        "سورة يوسف": "Yusuf",
        "سورة الرعد": "Ar-Ra'd",
        "سورة إبراهيم": "Ibrahim",
        "سورة الحجر": "Al-Hijr",
        "سورة النحل": "An-Nahl",
        "سورة الإسراء": "Al-Isra",
        "سورة الكهف": "Al-Kahf",
        "سورة مريم": "Maryam",
        "سورة طه": "Ta-Ha",
        "سورة الأنبياء": "Al-Anbiya",
        "سورة الحج": "Al-Hajj",
        "سورة المؤمنون": "Al-Mu'minun",
        "سورة النور": "An-Nur",
        "سورة الفرقان": "Al-Furqan",
        "سورة الشعراء": "Ash-Shu'ara",
        "سورة النمل": "An-Naml",
        "سورة القصص": "Al-Qasas",
        "سورة العنكبوت": "Al-Ankabut",
        "سورة الروم": "Ar-Rum",
        "سورة لقمان": "Luqman",
        "سورة السجدة": "As-Sajdah",
        "سورة الأحزاب": "Al-Ahzab",
        "سورة سبأ": "Saba",
        "سورة فاطر": "Fatir",
        "سورة يس": "Ya-Sin",
        "سورة الصافات": "As-Saffat",
        "سورة ص": "Sad",
        "سورة الزمر": "Az-Zumar",
        "سورة غافر": "Ghafir",
        "سورة فصلت": "Fussilat",
        "سورة الشورى": "Ash-Shura",
        "سورة الزخرف": "Az-Zukhruf",
        "سورة الدخان": "Ad-Dukhan",
        "سورة الجاثية": "Al-Jathiyah",
        "سورة الأحقاف": "Al-Ahqaf",
        "سورة محمد": "Muhammad",
        "سورة الفتح": "Al-Fath",
        "سورة الحجرات": "Al-Hujurat",
        "سورة ق": "Qaf",
        "سورة الذاريات": "Adh-Dhariyat",
        "سورة الطور": "At-Tur",
        "سورة النجم": "An-Najm",
        "سورة القمر": "Al-Qamar",
        "سورة الرحمن": "Ar-Rahman",
        "سورة الواقعة": "Al-Waqi'ah",
        "سورة الحديد": "Al-Hadid",
        "سورة المجادلة": "Al-Mujadilah",
        "سورة الحشر": "Al-Hashr",
        "سورة الممتحنة": "Al-Mumtahanah",
        "سورة الصف": "As-Saff",
        "سورة الجمعة": "Al-Jumu'ah",
        "سورة المنافقون": "Al-Munafiqun",
        "سورة التغابن": "At-Taghabun",
        "سورة الطلاق": "At-Talaq",
        "سورة التحريم": "At-Tahrim",
        "سورة الملك": "Al-Mulk",
        "سورة القلم": "Al-Qalam",
        "سورة الحاقة": "Al-Haqqah",
        "سورة المعارج": "Al-Ma'arij",
        "سورة نوح": "Nuh",
        "سورة الجن": "Al-Jinn",
        "سورة المزمل": "Al-Muzzammil",
        "سورة المدثر": "Al-Muddaththir",
        "سورة القيامة": "Al-Qiyamah",
        "سورة الإنسان": "Al-Insan",
        "سورة المرسلات": "Al-Mursalat",
        "سورة النبأ": "An-Naba",
        "سورة النازعات": "A-Naziat",
        "سورة عبس": "Abasa",
        "سورة التكوير": "At-Takwir",
        "سورة الإنفطار": "Al-Infitar",
        "سورة المطففين": "Al-Mutaffifin",
        "سورة الإنشقاق": "Al-Inshiqaq",
        "سورة البروج": "Al-Buruj",
        "سورة الطارق": "At-Tariq",
        "سورة الأعلى": "Al-A'la",
        "سورة الغاشية": "Al-Ghashiyah",
        "سورة الفجر": "Al-Fajr",
        "سورة البلد": "Al-Balad",
        "سورة الشمس": "Ash-Shams",
        "سورة الليل": "Al-Lail",
        "سورة الضحى": "Ad-Duha",
        "سورة الشرح": "Ash-Sharh",
        "سورة التين": "At-Tin",
        "سورة العلق": "Al-Alaq",
        "سورة القدر": "Al-Qadr",
        "سورة البينة": "Al-Bayyinah",
        "سورة الزلزلة": "Az-Zalzalah",
        "سورة العاديات": "Al-Adiyat",
        "سورة القارعة": "Al-Qari'ah",
        "سورة التكاثر": "At-Takathur",
        "سورة العصر": "Al-Asr",
        "سورة الهمزة": "Al-Humazah",
        "سورة الفيل": "Al-Fil",
        "سورة قريش": "Quraish",
        "سورة الماعون": "Al-Ma'un",
        "سورة الكوثر": "Al-Kauthar",
        "سورة الكافرون": "Al-Kafirun",
        "سورة النصر": "An-Nasr",
        "سورة المسد": "Al-Masad",
        "سورة الإخلاص": "Al-Ikhlas",
        "سورة الفلق": "Al-Falaq",
        "سورة الناس": "An-Nas",
        "لم يتم تحميل الآية بنجاح": "The verse was not downloaded successfully",
        "إالغاء": "Cancel",
        "ثابت": "Fixed",
        "مدرّج": "Gradient",
        "يدوي": "Manual",
        "انقر هنا لاختيار لون التطبيق": "Click here to choose the color of the application",
        "تغيير لون التطبيق": "Change the color of the application",
        "العثماني": "Uthmanic",
        "العثماني 2": "Uthmanic 2",
        "الكوفي": "Kufi",
        "النسخ": "Naskh",
        "العربي": "Arabic",
        "المدينة": "Madinah",
        "نور هيرا": "Noor Hira",
        "شهرزاد": "Shahrazad",
        "ملاحظات المستخدمين": "User Notes",
        "تم تحديث وقت الاشعار": "The notification time has been updated",
        "اذان العشاء": "Isha Adhan",
        "تبقى القليل لموعد اذان العشاء": "There is little left for the Isha Adhan",
        "تم تفعيل تذكير اذان العشاء": "Isha Adhan reminder has been activated",
        "سيصلك اشعار لتذكيرك باذان العشاء": "You will receive a notification to remind you of the Isha Adhan",
        "تم تعطيل الاشعار الخاص بالعشاء": "The Isha Adhan notification has been disabled",
        "لن يصلك اشعار اذان العشاء": "You will not receive a notification for the Isha Adhan",
        "اذان  لمغرب": "Maghrib Adhan",
        "تبقى القليل لموعد اذان المغرب": "There is little left for the Maghrib Adhan",
        "تم تفعيل تذكير اذان المغرب": "Maghrib Adhan reminder has been activated",
        "سيصلك اشعار لتذكيرك باذان المغرب": "You will receive a notification to remind you of the Maghrib Adhan",
        "تم تعطيل الاشعار ": "The Maghrib Adhan notification has been disabled",
        "لن يصلك اشعار اذان المغرب": "You will not receive a notification for the Maghrib Adhan",
        "اذان العصر": "Asr Adhan",
        "تبقى القليل لموعد اذان العصر": "There is little left for the Asr Adhan",
        "تم تفعيل تذكير اذان العصر": "Asr Adhan reminder has been activated",
        "سيصلك اشعار لتذكيرك باذان العصر": "You will receive a notification to remind you of the Asr Adhan",
        "لن يصلك اشعار اذان العصر": "You will not receive a notification for the Asr Adhan",
        "اذان الظهر": "Dhuhr Adhan",
        "تبقى القليل لموعد اذان الظهر": "There is little left for the Dhuhr Adhan",
        "تم تفعيل تذكير اذان الظهر": "Dhuhr Adhan reminder has been activated",
        "سيصلك اشعار لتذكيرك باذان الظهر": "You will receive a notification to remind you of the Dhuhr Adhan",
        "لن يصلك اشعار اذان الظهر": "You will not receive a notification for the Dhuhr Adhan",
        "تبقى القليل لموعد شروق الشمس": "There is little left for the sunrise",
        "تم تفعيل تذكير شروق الشمس": "Sunrise reminder has been activated",
        "سيصلك اشعار لتذكيرك بموعد شروق الشمس": "You will receive a notification to remind you of the sunrise",
        "لن يصلك اشعار  شروق الشمس": "You will not receive a notification for the sunrise",
        "اذان الفجر": "Fajr Adhan",
        "تبقى القليل لموعد اذان الفجر": "There is little left for the Fajr Adhan",
        "تم تفعيل تذكير اذان الفجر": "Fajr Adhan reminder has been activated",
        "سيصلك اشعار لتذكيرك باذان الفجر": "You will receive a notification to remind you of the Fajr Adhan",
        "لن يصلك اشعار اذان الفجر": "You will not receive a notification for the Fajr Adhan",
        "لا تنسى قراءة أذكار المساء ": "Do not forget to read the evening dhikr",
        "لأذكار المساء فضل عظيم لا تفوته": "For the evening dhikr, a great virtue not to be missed",
        "تم تفعيل تذكير أذكار المساء": "Evening dhikr reminder has been activated",
        "لن يصلك اشعار أذكار المساء": "You will not receive a notification for the evening dhikr",
        "لا تنسى قراءة أذكار الصباح ": "Do not forget to read the morning dhikr",
        "لأذكار الصباح فضل عظيم لا تفوته": "For the morning dhikr, a great virtue not to be missed",
        "تم تفعيل تذكير أذكار الصباح": "Morning dhikr reminder has been activated",
        "لن يصلك اشعار أذكار الصباج": "You will not receive a notification for the morning dhikr",
        "اذكر الله": "Do Thikr",
        "تم تفعيل الذكر العشوائي": "Random dhikr has been activated",
        "سيصلك اشعار بأذكار مختلفة": "You will receive a notification for different dhikr",
        "لن يصلك اشعار الذكر العشوائي": "You will not receive a notification for the random dhikr",
        "لا تنسى صيام غدا فهو من الايام البيض ": "Do not forget to fast tomorrow, it is from the white days",
        "كان صلى الله عليه وسلم يصوم ثلاثة ايام من كل شهر هجري":
            "The Prophet (s.a.w.) used to fast three days of every Hijri month",
        "تم تفعيل تذكير صيام الايام البيض": "White days fasting reminder has been activated",
        "سيصلك اشعار لتذكيرك بالصوم": "You will receive a notification to remind you of fasting",
        "لن يصلك اشعار صيام الايام البيض": "You will not receive a notification for the white days fasting",
        "لا تنسى صيام غدا الخميس ": "Do not forget to fast tomorrow, it is Thursday",
        "كان صلى الله عليه وسلم يصوم يومي الاثنين والخميس من كل اسبوع":
            "The Prophet (s.a.w.) used to fast on Mondays and Thursdays of every week",
        "تم تفعيل تذكير صيام يوم الخميس": "Thursday fasting reminder has been activated",
        "سيصلك اشعار لتذكيرك بالصوم يوم الاربعاء":
            "You will receive a notification to remind you of fasting on Thursday",
        "لن يصلك اشعار صيام يوم الخميس": "You will not receive a notification for the Thursday fasting",
        "لا تنسى صيام غدا الاثنين ": "Do not forget to fast tomorrow, it is Monday",
        "تم تفعيل تذكير صيام يوم الاثنين ": "Monday fasting reminder has been activated",
        "سيصلك اشعار لتذكيرك بالصوم يوم الاحد": "You will receive a notification to remind you of fasting on Monday",
        "لن يصلك اشعار صيام يوم الاثنين": "You will not receive a notification for the Monday fasting",
        "لا تنسى قراءة وردك اليومي من القرآن ": "Do not forget to read your daily portion of the Quran",
        " قَالَ رَسُولُ اللَّهِ ﷺ:  ((اقْرَءُوا الْقُرْآنَ فَإِنَّهُ يَأْتِي يَوْمَ الْقِيَامَةِ شَفِيعًا لأَصْحَابِهِ))":
            "The Messenger of Allah (s.a.w.) said: ((Read the Quran, for it will come on the Day of Resurrection interceding for its companions))",
        "تم تفعيل تذكير قراءة الورد اليومي للقران": "Daily Quran portion reminder has been activated",
        "سيصلك اشعار لتذكيرك بقراءة وردك اليومي من القرآن الكريم":
            "You will receive a notification to remind you of your daily portion of the Quran",
        "لن يصلك اشعار قراءة الورد اليومي للقران": "You will not receive a notification for the daily Quran portion",
        "لا تنسى قراءة سورة الكهف ": "Do not forget to read Surat Al-Kahf",
        " قَالَ رَسُولُ اللَّهِ ﷺ:  ((مَن قَرَأَ سورةَ الكَهفِ يومَ الجُمُعةِ أضاءَ له من النورِ ما بَينَ الجُمُعتينِ  ))":
            "The Messenger of Allah (s.a.w.) said: ((Whoever reads Surat Al-Kahf on Friday, light will shine for him between the two Fridays))",
        "تم تفعيل تذكير قراءة سورة الكهف": "Surat Al-Kahf reminder has been activated",
        "سيصلك اشعار لتذكيرك بقراءة سورة الكهف":
            "You will receive a notification to remind you of reading Surat Al-Kahf",
        "لن يصلك اشعار قراءة سورة الكهف": "You will not receive a notification for reading Surat Al-Kahf",
        "سيصلك اشعار بحديث عن رسول الله": "You will receive a notification for a hadith about the Messenger of Allah",
        "تم تفعيل تذكير حديث عن رسول الله": "Hadith reminder has been activated",
        "لن يصلك اشعار حديث عن رسول الله":
            "You will not receive a notification for a hadith about the Messenger of Allah",

        //--------------------------------------------------------------------------------
        "اللَّهُ": "Allah",
        "وهو الاسم الأعظم الذي تفرد به الحق سبحانه وخص به نفسه وجعله أول أسمائه، وأضافها كلها إليه فهو علم على ذاته سبحانه":
            "And He is the Greatest Name that the Truth has singled out and made it special and made it the first of His names, and added all of them to Him, so He is a science on His own, glory be to Him",
        "الرَّحْمَنُ": "The Most Merciful",
        "كثير الرحمة وهو اسم مقصور على الله عز وجل ولا يجوز أن يقال رحمن لغير الله، وذلك لأن رحمته وسعت كل شيء وهو أرحم الراحمين":
            "He is the Most Merciful, and He is a name that is limited to God Almighty, and it is not permissible to say Rahman for other than God, because His mercy has encompassed everything, and He is the Most Merciful of the Merciful",
        "الرَّحِيمُ": "The Most Gracious",
        "هو المنعم أبدا، المتفضل دوما، فرحمته لا تنتهي":
            "He is the Benefactor forever, the Benefactor always, so His mercy does not end",
        "المَلِكُ": "The King",
        "هو الله، ملك الملوك، له الملك، وهو مالك يوم الدين، ومليك الخلق فهو المالك المطلق":
            "He is God, the King of Kings, to Him is the kingdom, and He is the owner of the Day of Judgment, and the King of creation, so He is the absolute owner",
        "بسم الله الرحمن الرحيم\n1- باب الإخلاص وإحضار النية في جميع الأعمال والأقوال والأحوال البارزة والخفية، قَالَ اللهُ تَعَالَى: {وَمَا أُمِرُوا إِلاَّ لِيَعْبُدُوا اللَّهَ مُخْلِصِينَ لَهُ الدِّينَ حُنَفَاءَ وَيُقِيمُوا الصَّلاةَ وَيُؤْتُوا الزَّكَاةَ وَذَلِكَ دِينُ الْقَيِّمَةِ} [البينة : 5]، وَقالَ تَعَالَى: {لَنْ يَنَالَ اللَّهَ لُحُومُهَا وَلا دِمَاؤُهَا وَلَكِنْ يَنَالُهُ التَّقْوَى مِنْكُمْ} [الحج: 37]، وَقالَ تَعَالَى: {قُلْ إِنْ تُخْفُوا مَا فِي صُدُورِكُمْ أَوْ تُبْدُوهُ يَعْلَمْهُ اللَّهُ} [آل عمران: 29].":
            "In the name of Allah, the Most Gracious, the Most Merciful\n1- The chapter of sincerity and bringing the intention in all works, words, and prominent and hidden conditions, Allah Almighty said: {And they were not commanded except to worship Allah, [being] sincere to Him in religion, inclining to truth, and to establish prayer and to give zakah. And that is the correct religion} [Al-Bayyinah: 5], and Allah Almighty said: {Their meat will not reach Allah, nor will their blood, but what reaches Him is piety from you} [Al-Hajj: 37], and Allah Almighty said: {Say, \"Whether you conceal what is in your breasts or reveal it, Allah knows it} [Al-Imran: 29].",
        "(إنّمَا الأَعْمَالُ بالنِّيّاتِ، وَإِنَّمَا لِكُلِّ امرِىءٍ مَا نَوَى، فَمَنْ كَانَتْ هجرته إلى الله ورسوله، فهجرته إلى الله ورسوله، ومن كانت هِجْرَتُهُ لِدُنْيَا يُصيبُهَا، أَوْ امْرَأَةٍ يَنْكَحُهَا، فَهِجْرَتُهُ إِلى مَا هَاجَرَ إِلَيْه). مُتَّفَقٌ عَلَى صِحَّتِهِ. رَوَاهُ إمَامَا الْمُحَدّثِينَ، أبُو عَبْدِ الله مُحَمَّدُ بْنُ إسْمَاعيلَ بْن إبراهِيمَ بْن المُغيرَةِ بنِ بَرْدِزْبهْ الجُعْفِيُّ البُخَارِيُّ، وَأَبُو الحُسَيْنِ مُسْلمُ بْنُ الحَجَّاجِ بْنِ مُسْلمٍ الْقُشَيريُّ النَّيْسَابُورِيُّ رضي اللهُ عنهما فِي صحيحيهما اللَّذَيْنِ هما أَصَحُّ الكُتبِ المصنفةِ.":
            "Actions are judged by intentions, and each person will be rewarded according to their intentions. So, whoever migrates for the sake of Allah and His Messenger, their migration is for Allah and His Messenger. And whoever migrates for worldly gain or to marry a woman, their migration is for what they migrated for.",
        "قالَ رسول الله صلى الله عليه وسلم: (يغْزُو جَيْشٌ الْكَعْبَةَ فإِذَا كَانُوا بِبَيْدَاءَ مِنَ الأَرضِ يُخْسَفُ بِأَوَّلِهِمْ وآخِرِهِمْ). قَالَتْ: قلتُ: يَا رَسُولَ اللهِ، كَيْفَ يُخْسَفُ بأوَّلِهِمْ وَآخِرِهِمْ وَفِيهمْ أسْوَاقُهُمْ(1)، وَمَنْ لَيْسَ مِنْهُمْ ؟! قَالَ: (يُخْسَفُ بِأَوَّلِهِمْ وَآخِرِهِمْ ثُمَّ يُبْعَثُونَ عَلَى نِيّاتِهمْ) مُتَّفَقٌ عَلَيهِ. هذَا لَفْظُ الْبُخَارِيِّ .\n\n\nـــــــــــــــ\n(1) السوقة من الناس: الرعية ومن دون الملك ومن لم يكن ذا سلطان، والذكر والأنثى فيه سواء. اللسان 6/437 (سوق).":
            "Allah's Messenger (sallallahu aleyhi ve sellem) said: An army will attack the Ka'bah and when they are in a desert plain, the first and last of them will be swallowed up by the earth. I said: O Messenger of Allah, how will they be swallowed up when amongst them will be their markets (1) and those who are not among them? He said: They will all be swallowed up, then they will be resurrected according to their intentions.",
        "قَالَ النبي صلى الله عليه وسلم: (لا هِجْرَةَ بَعْدَ الفَتْحِ، وَلَكِنْ جِهَادٌ وَنِيَّةٌ، وَإِذَا اسْتُنْفِرْتُمْ(1) فانْفِرُوا) مُتَّفَقٌ عَلَيْهِ.\n\n\nـــــــــــــ\n(1) الاستنفار: الاستنجاد والاستنصار: أي إذا طلب منكم النصرة فأجيبوا وانفروا خارجين إلى الإعانة. النهاية 5/95.a":
            "Allah's Messenger (sallallahu aleyhi ve sellem) said: There is no migration after the conquest of Makkah, but there is jihad and intention. And when you are called (1), then go forth.",
        "كُنَّا مَعَ النَّبيِّ صلى الله عليه وسلم في غَزَاةٍ، فَقالَ: (إِنَّ بالمدِينَةِ لَرِجَالاً ما سِرْتُمْ مَسِيراً، وَلاَ قَطَعْتُمْ وَادِياً، إلاَّ كَانُوا مَعَكمْ حَبَسَهُمُ الْمَرَضُ). وَفي روَايَة: (إلاَّ شَرَكُوكُمْ في الأجْرِ)رواهُ مسلمٌ. ورواهُ البخاريُّ عن أنسٍ رضي الله عنه قَالَ: رَجَعْنَا مِنْ غَزْوَةِ تَبُوكَ مَعَ النَّبيِّ صلى الله عليه وسلم فقال : (إنَّ أقْواماً خَلْفَنَا بالْمَدِينَةِ مَا سَلَكْنَا شِعْباً (1)، وَلاَ وَادياً، إلاّ وَهُمْ مَعَنَا؛ حَبَسَهُمُ العُذْرُ).\n\nـــــــــــــ\n(1) الشِّعب: ما انفرج بين جبلين. اللسان 7/126 (شعب).":
            "We were with the Prophet (peace be upon him) in a battle, and he said, Verily, in Madinah there are men who did not accompany you on any path or cross any valley, but they are with you because they were prevented by illness. In another narration, it says, Except that they shared in the reward. This hadith is narrated by Muslim. Al-Bukhari also narrated from Anas (may Allah be pleased with him) that he said, We returned from the Battle of Tabuk with the Prophet (peace be upon him), and he said, 'There are people who stayed behind in Madinah, and whenever we traversed a mountain pass or a valley, they were with us; their excuse held them back.",
        "كَانَ أبي يَزيدُ أخْرَجَ دَنَانِيرَ يَتَصَدَّقُ بِهَا، فَوَضعَهَا عِنْدَ رَجُلٍ في الْمَسْجِدِ، فَجِئْتُ فأَخذْتُها فَأَتَيْتُهُ بِهَا. فقالَ: واللهِ، مَا إيَّاكَ أرَدْتُ، فَخَاصَمْتُهُ إِلى رسولِ اللهِ صلى الله عليه وسلم، فقَالَ: (لكَ مَا نَوَيْتَ يَا يزيدُ، ولَكَ ما أخَذْتَ يَا مَعْنُ). رواهُ البخاريُّ.":
            "My father, Yazid, used to take out some dinars to give in charity. He placed them with a man in the mosque, and when I came, I took them and brought them to him. He said, By Allah, I did not intend for you specifically. So, I disputed the matter with him before the Messenger of Allah (peace be upon him). The Messenger of Allah (peace be upon him) said, You have what you intended, O Yazid, and you have what you took, O Ma'n. This hadith is narrated by Al-Bukhari.",
        "جاءنِي رسولُ اللهِ صلى الله عليه وسلم يَعُودُنِي عَامَ حَجَّةِ الوَدَاعِ مِنْ وَجَعٍ اشْتَدَّ بي، فقُلْتُ: يَا رَسُولَ اللهِ، إنِّي قَدْ بَلَغَ بي مِنَ الوَجَعِ مَا تَرَى، وَأَنَا ذُو مالٍ وَلا يَرِثُني إلا ابْنَةٌ لي، أفأَتَصَدَّقُ بِثُلُثَيْ مَالِي؟ قَالَ: (لا)، قُلْتُ: فالشَّطْرُ يَا رَسُولَ اللهِ؟ فقَالَ: (لا)، قُلْتُ: فالثُّلُثُ يَا رَسُولَ اللهِ؟ قَالَ: (الثُّلُثُ والثُّلُثُ كَثيرٌ - أَوْ كبيرٌ - إنَّكَ إنْ تَذَرْ وَرَثَتَكَ أغنِيَاءَ خيرٌ مِنْ أنْ تَذَرَهُمْ عَالَةً (1)، يتكفَّفُونَ النَّاسَ، وَإنَّكَ لَنْ تُنفِقَ نَفَقَةً تَبْتَغي بِهَا وَجهَ اللهِ إلاَّ أُجِرْتَ عَلَيْهَا حَتَّى مَا تَجْعَلُ في فِيِّ امْرَأَتِكَ)، قَالَ: فَقُلتُ: يَا رسولَ اللهِ، أُخلَّفُ (2)، بعدَ أصْحَابي؟ قَالَ: (إِنَّكَ لَنْ تُخَلَّفَ فَتَعملَ عَمَلاً تَبتَغي بِهِ وَجْهَ اللهِ إلاَّ ازْدَدتَ بِهِ دَرَجةً ورِفعَةً، وَلَعلَّكَ أنْ تُخَلَّفَ حَتّى يَنتَفِعَ بِكَ أقْوَامٌ وَيُضَرَّ بِكَ آخرونَ. اللَّهُمَّ أَمْضِ لأصْحَابي هِجْرَتَهُمْ ولاَ تَرُدَّهُمْ عَلَى أعقَابهمْ، لكنِ البَائِسُ سَعدُ بْنُ خَوْلَةَ) يَرْثي لَهُ رَسُولُ اللهِ صلى الله عليه وسلم أنْ ماتَ بمَكَّة. مُتَّفَقٌ عليهِ .\n\nـــــــــــــ\n(1)  جمع عائل، وهو الفقير. النهاية 3/323 .\n(2) التخلف: التأخر. النهاية 2/67 ":
            "The Messenger of Allah (peace be upon him) came to me during the Farewell Pilgrimage, while I was suffering from severe pain. I said, O Messenger of Allah, the pain I am experiencing has become unbearable, and I have wealth but no heir except for my daughter. Should I give two-thirds of my wealth in charity? He said, No. I asked, Then half of it, O Messenger of Allah? He replied, No. I inquired further, One-third, O Messenger of Allah? He said, One-third and even one-third is a lot. It is better for you to leave your heirs wealthy and independent than to leave them begging from people. They would be better off financially. And if you spend a small amount seeking the pleasure of Allah, you will be rewarded for it until you don't even leave a coin in your pocket for your wife. I said, O Messenger of Allah, what about my relatives after my companions? He said, You will never be left behind, and any good deed you do seeking the pleasure of Allah will elevate your status. Perhaps you will be left behind so that some people will benefit from you while others will be harmed. O Allah, grant my companions success in their migrations and do not make them return in failure. But the unfortunate one is Sa'd ibn Khawlah. The Messenger of Allah (peace be upon him) lamented his death in Makkah. This hadith is agreed upon as authentic.",
        "قَالَ رَسُولُ الله صلى الله عليه وسلم : (إنَّ الله لا ينْظُرُ إِلى أجْسَامِكُمْ، ولا إِلى صُوَرِكمْ، وَلَكن ينْظُرُ إلى قُلُوبِكمْ وأعمالكم) رواه مسلم.":
            "The Messenger of Allah (peace be upon him) said, Verily, Allah does not look at your outward appearances or your physical forms, but He looks at your hearts and your deeds. This hadith is narrated by Muslim.",
        " سُئِلَ رسولُ الله صلى الله عليه وسلم عَنِ الرَّجُلِ يُقاتلُ شَجَاعَةً، ويُقَاتِلُ حَمِيَّةً، ويُقَاتِلُ رِيَاءً، أَيُّ ذلِكَ في سبيلِ الله؟ فقال رَسُول الله aصلى الله عليه وسلم: (مَنْ قَاتَلَ لِتَكونَ كَلِمَةُ اللهِ هي العُلْيَا، فَهوَ في سبيلِ اللهِ) مُتَّفَقٌ عَلَيهِ.":
            "The Messenger of Allah (peace be upon him) was asked about a man who fights out of bravery, out of tribal loyalty, and out of seeking fame. Which of these motives is considered fighting in the cause of Allah? The Messenger of Allah (peace be upon him) replied,Whoever fights to make the word of Allah the highest, then he is fighting in the cause of Allah. This hadith is agreed upon as authentic.",
        "أَنَّ النَّبيَّ صلى الله عليه وسلم قَالَ: (إِذَا التَقَى المُسلِمَان بسَيْفَيهِمَا فالقَاتِلُ وَالمَقْتُولُ في النّارِ) قُلتُ: يا رَسُولَ اللهِ، هذا القَاتِلُ فَمَا بَالُ المقْتُولِ؟ قَالَ: (إنَّهُ كَانَ حَريصاً عَلَى قتلِ صَاحِبهِ) مُتَّفَقٌ عليهِ.":
            "The Prophet (peace be upon him) said, When two Muslims meet each other with their swords, both the killer and the killed will be in the Fire (of Hell). I asked, O Messenger of Allah, the killer is understandable, but what about the killed? He replied, He intended to kill his companion. This hadith is agreed upon as authentic.",
        "قالَ رَسُول الله صلى الله عليه وسلم: (صَلاةُ الرَّجلِ في جمَاعَةٍ تَزيدُ عَلَى صَلاتهِ في سُوقِهِ وبيتهِ بضْعاً (1)، وعِشرِينَ دَرَجَةً، وَذَلِكَ أنَّ أَحدَهُمْ إِذَا تَوَضَّأَ فَأَحْسَنَ الوُضوءَ، ثُمَّ أَتَى المَسْجِدَ لا يُرِيدُ إلاَّ الصَّلاةَ، لاَ يَنْهَزُهُ إِلاَّ الصَلاةُ: لَمْ يَخْطُ خُطْوَةً إِلاَّ رُفِعَ لَهُ بِهَا دَرجَةٌ، وَحُطَّ عَنْهُ بها خَطِيئَةٌ حَتَّى يَدْخُلَ المَسْجِدَ، فإِذا دَخَلَ المَسْجِدَ كَانَ في الصَّلاةِ مَا كَانَتِ الصَّلاةُ هِي تَحْبِسُهُ، وَالمَلائِكَةُ يُصَلُّونَ عَلَى أَحَدِكُمْ مَا دَامَ في مَجْلِسِهِ الَّذِي صَلَّى فِيهِ، يَقُولُونَ: اللَّهُمَّ ارْحَمْهُ، اللَّهُمَّ اغْفِرْ لَهُ، اللَّهُمَّ تُبْ عَلَيهِ، مَا لَم يُؤْذِ فيه، مَا لَمْ يُحْدِثْ فِيهِ). مُتَّفَقٌ عليه، وهذا لفظ مسلم.\nوقوله صلى الله عليه وسلم: (يَنْهَزُهُ) هُوَ بِفَتْحِ اليَاءِ والْهَاءِ وبالزَّايِ: أَيْ يُخْرِجُهُ ويُنْهضُهُ.\n\nـــــــــــــ\n(1)  البضع: في العدد بالكسر، وقد يفتح ما بين الثلاث إلى التسع. وقيل: ما بين الواحد إلى العشرة، لأنه قطعة من العدد. النهاية 1/132 .":
            "The Prophet (peace be upon him) said, When two Muslims meet each other with their swords, both the killer and the killed will be in the Fire (of Hell). I asked, O Messenger of Allah, the killer is understandable, but what about the killed? He replied, He intended to kill his companion. This hadith is agreed upon as authentic.",
        "عن رَسُول الله صلى الله عليه وسلم، فيما يروي عن ربهِ، تباركَ وتعالى، قَالَ: (إنَّ اللهَ كَتَبَ الحَسَنَاتِ والسَّيِّئَاتِ ثُمَّ بَيَّنَ ذلِكَ، فَمَنْ هَمَّ (1)، بحَسَنَةٍ فَلَمْ يَعْمَلْهَا كَتَبَها اللهُ تَبَارَكَ وتَعَالى عِنْدَهُ حَسَنَةً كامِلَةً، وَإنْ هَمَّ بهَا فَعَمِلَهَا كَتَبَهَا اللهُ عَشْرَ حَسَناتٍ إِلى سَبْعمئةِ ضِعْفٍ إِلى أَضعَافٍ كَثيرةٍ، وإنْ هَمَّ بِسَيِّئَةٍ فَلَمْ يَعْمَلْهَا كَتَبَهَا اللهُ تَعَالَى عِنْدَهُ حَسَنَةً كَامِلةً، وَإنْ هَمَّ بِهَا فَعَمِلَهَا كَتَبَهَا اللهُ سَيِّئَةً وَاحِدَةً) مُتَّفَقٌ عليهِ.\n\nـــــــــــــ\n(1) همّ بالأمر يهمّ، إذا عزم عليه. النهاية 5/274 .":
            "This hadith narrates that the Prophet Muhammad, peace be upon him, said, quoting Allah Almighty:   Allah has recorded the good and the evil deeds. Then He made it clear that whoever intends to do a good deed but does not do it, Allah will write it down as a complete good deed with Him. And if he intends to do it and actually does it, Allah will write it down as ten good deeds up to seven hundred times, or many more. And if he intends to do an evil deed but does not do it, Allah will write it down as a complete good deed with Him. And if he intends to do it and actually does it, Allah will write it down as one evil deed. This hadith emphasizes the importance of intentions in our actions. If we have good intentions and strive to do good deeds, Allah rewards us generously. Even if we are unable to fulfill our intentions, Allah still rewards us for the sincere intention. On the other hand, if we have evil intentions and act upon them, we are held accountable for our actions.",
        "(انطَلَقَ ثَلاثَةُ نَفَرٍ (1)، مِمَّنْ كَانَ قَبْلَكُمْ حَتَّى آوَاهُمُ المَبيتُ إِلى غَارٍ فَدَخلُوهُ، فانْحَدرَتْ صَخْرَةٌ مِنَ الجَبَلِ فَسَدَّتْ عَلَيْهِمُ الغَارَ، فَقالُوا: إِنَّهُ لاَ يُنْجِيكُمْ مِنْ هذِهِ الصَّخْرَةِ إِلاَّ أنْ تَدْعُوا اللهَ بصَالِحِ أعْمَالِكُمْ. قَالَ رجلٌ مِنْهُمْ: اللَّهُمَّ كَانَ لِي أَبَوانِ شَيْخَانِ كبيرانِ، وكُنْتُ لا أغْبِقُ (2)، قَبْلَهُمَا أهْلاً ولاَ مالاً، فَنَأَى (3)، بِي طَلَب الشَّجَرِ يَوْماً فلم أَرِحْ عَلَيْهمَا حَتَّى نَامَا، فَحَلَبْتُ لَهُمَا غَبُوقَهُمَا فَوَجَدْتُهُما نَائِمَينِ، فَكَرِهْتُ أنْ أُوقِظَهُمَا وَأَنْ أغْبِقَ قَبْلَهُمَا أهْلاً أو مالاً، فَلَبَثْتُ - والْقَدَحُ عَلَى يَدِي - أنتَظِرُ اسْتِيقَاظَهُما حَتَّى بَرِقَ الفَجْرُ والصِّبْيَةُ يَتَضَاغَوْنَ (4)، عِنْدَ قَدَميَّ، فاسْتَيْقَظَا فَشَرِبا غَبُوقَهُما. اللَّهُمَّ إنْ كُنْتُ فَعَلْتُ ذلِكَ ابِتِغَاء وَجْهِكَ فَفَرِّجْ عَنّا مَا نَحْنُ فِيهِ مِنْ هذِهِ الصَّخْرَةِ، فانْفَرَجَتْ شَيْئاً لا يَسْتَطيعُونَ الخُروجَ مِنْهُ. قَالَ الآخر: اللَّهُمَّ إنَّهُ كانَتْ لِيَ ابْنَةُ عَمّ، كَانَتْ أَحَبَّ النّاسِ إليَّ - وفي رواية: كُنْتُ أُحِبُّها كأَشَدِّ مَا يُحِبُّ الرِّجَالُ النساءَ - فأَرَدْتُهَا عَلَى نَفْسِهَا (5)، فامْتَنَعَتْ منِّي حَتَّى أَلَمَّتْ بها سَنَةٌ مِنَ السِّنِينَ فَجَاءتْنِي فَأَعْطَيْتُهَا عِشْرِينَ وَمئةَ دينَارٍ عَلَى أنْ تُخَلِّيَ بَيْني وَبَيْنَ نَفْسِهَا فَفعَلَتْ، حَتَّى إِذَا قَدَرْتُ عَلَيْهَا - وفي رواية: فَلَمَّا قَعَدْتُ بَينَ رِجْلَيْهَا، قالتْ: اتَّقِ اللهَ وَلاَ تَفُضَّ الخَاتَمَ إلاّ بِحَقِّهِ (6)، فَانصَرَفْتُ عَنْهَا وَهيَ أَحَبُّ النَّاسِ إليَّ وَتَرَكْتُ الذَّهَبَ الَّذِي أعْطَيتُها. اللَّهُمَّ إنْ كُنْتُ فَعَلْتُ ذلِكَ ابْتِغاءَ وَجْهِكَ فافْرُجْ عَنَّا مَا نَحْنُ فيهِ، فانْفَرَجَتِ الصَّخْرَةُ، غَيْرَ أَنَّهُمْ لا يَسْتَطِيعُونَ الخُرُوجَ مِنْهَا. وَقَالَ الثَّالِثُ: اللَّهُمَّ اسْتَأْجَرْتُ أُجَرَاءَ وأَعْطَيْتُهُمْ أجْرَهُمْ غيرَ رَجُل واحدٍ تَرَكَ الَّذِي لَهُ وَذَهبَ، فَثمَّرْتُ أجْرَهُ حَتَّى كَثُرَتْ مِنهُ الأمْوَالُ، فَجَاءنِي بَعدَ حِينٍ، فَقالَ: يَا عبدَ اللهِ، أَدِّ إِلَيَّ أجْرِي، فَقُلْتُ: كُلُّ مَا تَرَى مِنْ أجْرِكَ: مِنَ الإبلِ وَالبَقَرِ والْغَنَمِ والرَّقيقِ، فقالَ: يَا عبدَ اللهِ، لاَ تَسْتَهْزِىءْ بي! فَقُلْتُ: لاَ أسْتَهْزِئ بِكَ، فَأَخَذَهُ كُلَّهُ فاسْتَاقَهُ فَلَمْ يتْرُكْ مِنهُ شَيئاً. الَّلهُمَّ إنْ كُنتُ فَعَلْتُ ذلِكَ ابِتِغَاءَ وَجْهِكَ فافْرُجْ عَنَّا مَا نَحنُ فِيهِ، فانْفَرَجَتِ الصَّخْرَةُ فَخَرَجُوا يَمْشُونَ) (7)، مُتَّفَقٌ عليهِ .\n\nـــــــــــــ\n(1) نفر: هو اسم جمع، يقع على جماعة الرجال خاصة ما بين الثلاثة إلى العشرة، ولا واحد له من لفظه. النهاية 5/93 .\n(2) لا أغبق: أي ما كنت أقدم عليهما أحداً في شرب نصيبهما من اللبن الذي يشربانه. والغبوق شرب آخر النهار مقابل الصبوح. النهاية 3/341 .\n(3) نأى: بَعُد.\n(4) أي: يتصايحون ويبكون.\n(5) كناية عن الجماع .\n(6) الفض: الكسر والفتح، والخاتم كناية عن الفرج وعذرة البكارة، وحقه التزويج المشروع. دليل الفالحين 1/84.\n(7) في الحديث: استحباب الدعاء حال الكرب والتوسل بصالح العمل، وفيه فضيلة بر الوالدين وفضل خدمتهما وإيثارهما على من سواهما، وفيه فضل العفاف، وفيه فضل حسن العهد وأداء الأمانة والسماحة في المعاملة وإثبات كرامات الأولياء وهو مذهب أهل الحق. انظر: دليل الفالحين 1/86 .\n":
            "Three individuals set out, among those who were before you, until nightfall compelled them to seek refuge in a cave. Then a rock fell from the mountain and sealed the entrance of the cave. They said, 'Nothing can save you from this rock except invoking Allah with the righteousness of your deeds.' One of them said, 'O Allah, I had elderly parents whom I used to serve before myself, both in terms of physical needs and wealth. One day, I was delayed in fetching fodder for them, and they fell asleep before I could return. When I came back and found them sleeping, I hesitated to wake them up or to feed my own animals before them. I waited at their feet until dawn, and the children were crying out of hunger. O Allah, if I did this seeking Your pleasure, then relieve us from this rock.' At once, the rock moved aside slightly, but they were unable to exit. The second person said, 'O Allah, I had a cousin whom I loved more than anyone else, and I wanted her for myself. I persisted in pursuing her for a year until she finally agreed. But just as I was about to have intercourse with her, she said, Fear Allah and do not remove the protection except rightfully. I left her alone, even though she was the dearest person to me, and I abandoned the gold I had given her. O Allah, if I did this seeking Your pleasure, then relieve us from this predicament.' Immediately, the rock moved aside a bit, but they still couldn't escape. The third person said, 'O Allah, I employed some workers and paid them their wages, but one of them left without taking his due. I invested his share, and it multiplied over time. After a while, he returned and requested his payment. I told him that all the cattle, sheep, and slaves he saw before him were his payment. He insisted that I should not make fun of him, and I assured him that I was serious. He took everything, leaving nothing behind. O Allah, if I did this seeking Your pleasure, then relieve us from this hardship.' Instantly, the rock moved aside, and they were able to walk out.",
      };
}
