import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {"tr": tr, "en": en};

  Map<String, String> get tr => {
        "تنشيط الوضع اليلي": "Gece Modunu Aktif Et",
        "الإعدادات": "Ayarlar",
        "انقر هنا لاختيار الوضع اليلي": "Gece Modunu Seçmek İçin Tıklayın",
        "تشفيل صوت الاشعارات": "Bildirim Sesi Etkinleştir",
        "عند تفعيل هذا الخيار سيتم تشفيل صوت الاشعارات":
            "Bu seçeneği etkinleştirdiğinizde, bildirim sesi etkinleştirilecektir",
        "لغة البرنامج": "Uygulama Dili",
        "قم بإختيار لغة البرنامج المناسبة لك": "Size uygun uygulama dili seçin",
        "عالي  20 قأكثر يوميا": "Yüksek 20 veya daha fazla günlük",
        "متوسط  11-19  يوميا": "Orta 11-19 günlük",
        "منخفض  5-10  يوميا": "Düşük 5-10 günlük",
        "نادر  1-5  يوميا": "Nadir 1-5 günlük",
        "غير مسموح": "İzin verilmiyor",
        "لا يمكنك تغيير الاشعارات الخاصة بهذه الصلاة": "Bu namazın bildirimlerini değiştiremezsiniz",
        "حسنا": "Tamam",
        "المنبه": "Alarm",
        "تذكير الاحاديث": "Hadis Hatırlatıcısı",
        "الأذكار اليومية": "Günlük Zikirler",
        "قراءة القرآن": "Kuran Okuma",
        "اوقات الصيام": "Oruç Zamanları",
        "اوقات الاذان": "Namaz Vakitleri",
        "أذكار عشوائية": "Rastgele Zikirler",
        "سيصلك اشعار بذكر عشوائي": "Rastgele bir zikir bildirimi alacaksınız",
        "أذكار الصباح": "Sabah Zikirleri",
        "سيصلك اشعار لتذكيرك بقراءة أذكار الصباح": "Sabah zikirlerini okumak için bir bildirim alacaksınız",
        "أذكار المساء": "Akşam Zikirleri",
        "سيصلك اشعار لتذكيرك بقراءة أذكار المساء": "Akşam zikirlerini okumak için bir bildirim alacaksınız",
        "قراءة صفحة من القرآن كل يوم": "Her gün bir sayfa Kuran oku",
        "سيصلك اشعار كل يوم لتذكيرك بقراءة صفحة من القرآن":
            "Her gün bir sayfa Kuran okumak için bir bildirim alacaksınız",
        "قراءة سورة الكهف": "Kehif Süresi Okuma",
        "سيصلك اشعار لتذكيرك بقراءة سورة الكهف يوم الجمعة":
            "Cuma günü Kehif süresi okumak için bir bildirim alacaksınız",
        "صيام الاثنين": "Pazartesi Orucu",
        "قم بالتفعيل ليصلك اشعار لتذكيرك بالصوم يومي الاثنين والخميس":
            "Pazartesi ve Perşembe günleri oruç tutmak için bir bildirim almak için etkinleştirin",
        "صيام الخميس": "Perşembe Orucu",
        "قم بالتفعيل ليصلك اشعار لتذكيرك بالصوم":
            "Perşembe günleri oruç tutmak için bir bildirim almak için etkinleştirin",
        "صيام الايام البيض": "Aşure Orucu",
        "حديث رسول الله ﷺ": "Peygamber Efendimiz'in Hadisi",
        "سيصلك اشعار بحديث رسول الله ﷺ": "Peygamber Efendimizin hadisiyle ilgili bir bildirim alacaksınız",
        "صلاة الفجر": "Sabah Namazı",
        "صلاة الظهر": "Öğle Namazı",
        "صلاة العصر": "İkindi Namazı",
        "صلاة المغرب": "Akşam Namazı",
        "صلاة العشاء": "Yatsı Namazı",
        "سيصلك اشعار قبل موعد الاذان بدقائق": "Namaz vaktinden dakikalar önce bir bildirim alacaksınız",
        "مراجعة القرآن": "Kuran'ı Gözden Geçirme",
        "اختبر حفظك للقران واختر رقم الصفحة والجزء للآية": "Kuran'ı ezberleme testi ve ayet için sayfa ve cüz seçin",
        "أسئلة بأزرار": "Düğmelerle Sorular",
        "أسئلة بقوائم": "Listelerle Sorular",
        "اختر طريقة الاجابة:": "Cevap verme yöntemini seçin:",
        "اختر جزء:": "Juz seç",
        "اختر الصفحة:": "Sayfa seç",
        "تأكيد": "Onayla",
        " خيارات ": " Seçenekler ",
        "التالي": "Sonraki",
        "نوع الاختبار:  ": "Test türü: ",
        "الايات": "Ayetler",
        "السور": "Süreler",
        "من الصفحة    ": "Sayfasından",
        "من الجزء    ": "juzdan",
        "الى الصفحة    ": "Sayfasına",
        "الى الجزء    ": "juz'a",
        "الاجابات الصحيحة:   ": "Doğru cevaplar: ",
        "الاجابات الخاطئة:  ": "Yanlış cevaplar: ",
        "المفضلة": "Favoriler",
        "الكل": "Hepsi",
        "أسماء الله": "Allah'ın İsimleri",
        "الأذكار": "Zikirler",
        "القرآن الكريم": "Kuran-ı Kerim",
        "الحديث الشريف": "Hadis-i Şerif",
        "بحث": "Arama",
        "موعد الصلاة القادمة": "Sonraki Namaz Vakti",
        "رفض": "Reddet",
        "ملاحظة للمطور": "Geliştiriciye Not",
        "الاسم :": "İsim :",
        "الملاحظة :": "Not :",
        "ارسال": "Gönder",
        "الرجاء التأكد من كتابة الاسم": "Lütfen ismi yazdığınızdan emin olun",
        "الرجاء التأكد من كتابة الملاحظة": "Lütfen notu yazdığınızdan emin olun",
        "تم ارسال الرسالة للمطور بنجاح": "Mesaj başarıyla geliştiriciye gönderildi",
        "حدث خطأ ما الرجاء المحاولة مرة اخرى": "Bir hata oluştu, lütfen tekrar deneyin",
        "العشاء": "Yatsı",
        "المغرب": "Akşam",
        "الفجر": "Sabah",
        "العصر": "İkindi",
        "الظهر": "Öğle",
        "شروق الشمس": "Güneşin doğuşu",
        "التاريخ الهجري": "Hicri Takvim",
        "التاريخ الميلادي": "Miladi Takvim",
        "تحديث": "Güncelleme",
        "اوقات الصلاة": "Namaz Vakitleri",
        "الجُزْءُ": "Cüz",
        "سُورَةُ ": "Sûre",
        "إبحث عن آية او سورة...": "Ayet veya Sûre ara...",
        "تعديل نوع الخط": "Yazı Tipini Değiştir",
        "حجم الخط": "Yazı Boyutu",
        "تغير الثيم": "Tema Değiştir",
        "اضافة علامة": "İşaretle",
        "لا محدود": "Sınırsız",
        "الآية   :  ": "Ayet   :  ",
        "المقطع :  ": "Cüz   :  ",
        "تكرار التلاوة:  ": "Tekrar Sayısı:  ",
        "اختر الآية:  ": "Ayet Seç:",
        "من الآية:  ": "Ayetten:",
        "الى الآية :  ": "Ayet'e:",
        "تحديد المقطع:": "Cüz Seç:",
        "القارئ:": "Okuyucu:",
        "اعدادات القراءة": "Okuma Ayarları",
        "الصفحة": "Sayfa",
        "قم باختيار نوع الخط المناسب لك": "Yazı Tipini Seç",
        "الرئيسية": "Ana Sayfa",
        "أسماء الله الحسنى": "Allah'ın İsimleri",
        "أذكار المسلم": "Müslümanın Zikirleri",
        "مختلف الأذكار": "Çeşitli Zikirler",
        "تعرّف على اسماء الله الحسنى": "Allah'ın İsimlerini Öğren",
        "سورة ": "Sûre",
        "الآية ": "Ayet",
        "حدث خطأ أثناء تشغيل الصوت": "Ses oynatılırken bir hata oluştu",
        "تم تحيل الآية بنجاح": "Ayet başarıyla işaretlendi",
        "مشكلة في الاتصال بالانترنت": "İnternet bağlantısında bir sorun oluştu",
        "لا يوجد اتصال بالانترنت": "İnternet bağlantısı yok",
        "جاري تحميل الآية": "Ayet yükleniyor",
        "حديث عن رسول الله ﷺ": "Peygamber Efendimiz ﷺ hakkında Hadis",
        "زاد المؤمن": "Zad Al-Mu'min",
        "تم نسخ النص بنجاح": "Metin başarıyla kopyalandı",
        "أذكار المنزل": "Ev Zikirleri",
        "أذكار الاستيقاظ": "Uyandığında Okunacak Dualar",
        'أذكار النوم': "Yatarken Okunacak Dualar",
        'أذكار السفر': "Yolculuk Duası",
        'أذكار الطعام': "Yemek Duası",
        'أذكار المسجد': "Mescide Giriş Duası",
        'أذكار الخلاء': "Tuvalet Duası",
        'أذكار الحج': "Hac Duası",
        "الكل >>>  ": "Hepsi >>>  ",
        " الصفحة ": "Sayfa",
        " الجزء ": "Cüz",
        "تم": "Tamam",
        "بلّغو عني ولوآية": "Bana bir ayet bildirin",
        "آية من القرآن الكريم": "Kur'an-ı Kerim'den bir ayet",
        "الجزء": "Cüz",
        "اقسام البرنامج": "Uygulama Bölümleri",
        "تم حذف النص من المفضلة": "Metin favorilerden kaldırıldı",
        "تم إضافة النص إلى المفضلة": "Metin favorilere eklendi",
        "الصفحات": "Sayfalar",
        "تم ازالة العلامة": "İşaret kaldırıldı",
        "تم اضافة العلامة": "İşaret eklendi",
        "الغاء": "İptal",
        "هل تود ازالة علامة القراءة من هذه الصفحة؟": "Bu sayfadan işareti kaldırmak istiyor musunuz?",
        "هل تود وضع علامة على هذه الصفحة؟": "Bu sayfaya işaret koymak istiyor musunuz?",
        "ازالة علامة قراءة": "İşareti Kaldır",
        "اضافة علامة قراءة": "İşaret Ekle",
        "ياسر الدوسري": "Yasser Al-Dosari",
        "ياسر السلامة": "Yasser Al-Salamah",
        "ابراهيم الدوسري": "Ibrahim Al-Dosari",
        "أيمن سويد": "Ayman Swayd",
        "الحصري": "Al-Husari",
        "المنشاوي": "Al-Menshawi",
        "عبد الباسط": "Abdul Basit",
        "العفاسي": "Al-Afasy",
        "عبد الله بصفر": "Abdullah Basfar",
        "ابو بكر الشاطري": "Abu Bakr Al-Shatri",
        "أحمد العجمي": "Ahmed Al-Ajmi",
        "اللَّهُ": "Allah",
        "وهو الاسم الأعظم الذي تفرد به الحق سبحانه وخص به نفسه وجعله أول أسمائه، وأضافها كلها إليه فهو علم على ذاته سبحانه":
            "O, Allah'tır. O, en büyük isimdir. O, Allah, kendisini özel kıldı ve kendisine özgü kıldı ve onu ilk isim olarak kıldı ve onu tüm isimlerle birlikte kıldı. O, kendi zatı üzerinde bilgili ve yücedir",
        "الرَّحْمَنُ": "Rahman",
        "كثير الرحمة وهو اسم مقصور على الله عز وجل ولا يجوز أن يقال رحمن لغير الله، وذلك لأن رحمته وسعت كل شيء وهو أرحم الراحمين":
            "Çok merhametli olan, rahmeti geniş o",
        "الرَّحِيمُ": "Rahim",
        "هو المنعم أبدا، المتفضل دوما، فرحمته لا تنتهي":
            "O, sonsuza kadar nimet veren, daima üstün olan, rahmeti bitmeyen",
        "المَلِكُ": "Mâlik",
        "هو الله، ملك الملوك، له الملك، وهو مالك يوم الدين، ومليك الخلق فهو المالك المطلق":
            "O, Allah'tır, kralların kralı, mülk O'nundur, o, mülkün sahibidir, o, yaratıkların kralıdır, o, mutlak sahibidir",
      };
  Map<String, String> get en => {
        "تنشيط الوضع اليلي": "Activate Dark Mode",
        "الإعدادات": "Settings",
        "انقر هنا لاختيار الوضع اليلي": "Click here to select dark mode",
        "تشفيل صوت الاشعارات": "Enable Notification Sound",
        "عند تفعيل هذا الخيار سيتم تشفيل صوت الاشعارات":
            "When you activate this option, the notification sound will be turned on",
        "لغة البرنامج": "App Language",
        "قم بإختيار لغة البرنامج المناسبة لك": "Choose the appropriate app language for you",
        "عالي  20 قأكثر يوميا": "High 20 or more daily",
        "متوسط  11-19  يوميا": "Medium 11-19 daily",
        "منخفض  5-10  يوميا": "Low 5-10 daily",
        "نادر  1-5  يوميا": "Rare 1-5 daily",
        "غير مسموح": "Not Allowed",
        "لا يمكنك تغيير الاشعارات الخاصة بهذه الصلاة": "You cannot change the notifications for this prayer",
        "حسنا": "Okay",
        "المنبه": "Alarm",
        "تذكير الاحاديث": "Hadith Reminder",
        "الأذكار اليومية": "Daily Remembrance",
        "قراءة القرآن": "Read Quran",
        "اوقات الصيام": "Fasting Times",
        "اوقات الاذان": "Prayer Times",
        "أذكار عشوائية": "Random Remembrance",
        "سيصلك اشعار بذكر عشوائي": "You will receive a random remembrance notification",
        "أذكار الصباح": "Morning Remembrance",
        "سيصلك اشعار لتذكيرك بقراءة أذكار الصباح":
            "You will receive a notification to remind you to read the morning remembrance",
        "أذكار المساء": "Evening Remembrance",
        "سيصلك اشعار لتذكيرك بقراءة أذكار المساء":
            "You will receive a notification to remind you to read the evening remembrance",
        "قراءة صفحة من القرآن كل يوم": "Read a page of the Quran every day",
        "سيصلك اشعار كل يوم لتذكيرك بقراءة صفحة من القرآن":
            "You will receive a notification every day to remind you to read a page of the Quran",
        "قراءة سورة الكهف": "Read Surat Al-Kahf",
        "سيصلك اشعار لتذكيرك بقراءة سورة الكهف يوم الجمعة":
            "You will receive a notification to remind you to read Surat Al-Kahf on Friday",
        "صيام الاثنين": "Monday Fasting",
        "قم بالتفعيل ليصلك اشعار لتذكيرك بالصوم يومي الاثنين والخميس":
            "Activate to receive a notification to remind you to fast on Mondays and Thursdays",
        "صيام الخميس": "Thursday Fasting",
        "قم بالتفعيل ليصلك اشعار لتذكيرك بالصوم": "Activate to receive a notification to remind you to fast",
        "صيام الايام البيض": "Ashura Fasting",
        "حديث رسول الله ﷺ": "Hadith of the Prophet Muhammad ﷺ",
        "سيصلك اشعار بحديث رسول الله ﷺ": "You will receive a notification with the Hadith of the Prophet Muhammad ﷺ",
        "صلاة الفجر": "Fajr Prayer",
        "صلاة الظهر": "Dhuhr Prayer",
        "صلاة العصر": "Asr Prayer",
        "صلاة المغرب": "Maghrib Prayer",
        "صلاة العشاء": "Isha Prayer",
        "سيصلك اشعار قبل موعد الاذان بدقائق": "You will receive a notification minutes before the prayer time",
        "مراجعة القرآن": "Quran Review",
        "اختبر حفظك للقران واختر رقم الصفحة والجزء للآية":
            "Test your memorization of the Quran and choose the page number and part of the verse",
        "أسئلة بأزرار": "Questions with Buttons",
        "أسئلة بقوائم": "Questions with Lists",
        "اختر طريقة الاجابة:": "Choose the answer method:",
        "اختر جزء:": "Choose a part:",
        "اختر الصفحة:": "Choose a page:",
        "تأكيد": "Confirm",
        " خيارات ": "Options",
        "التالي": "Next",
        "نوع الاختبار:  ": "Test Type: ",
        "الايات": "Ayahs",
        "السور": "Surahs",
        "من الصفحة    ": "From page",
        "من الجزء    ": "From part",
        "الى الصفحة    ": "To page",
        "الى الجزء    ": "To part",
        "الاجابات الصحيحة:   ": "Correct answers:",
        "الاجابات الخاطئة:  ": "Wrong answers:",
        "المفضلة": "Favorites",
        "الكل": "All",
        "أسماء الله": "Names of Allah",
        "الأذكار": "Remembrance",
        "القرآن الكريم": "Quran",
        "الحديث الشريف": "Hadith",
        "بحث": "Search",
        "موعد الصلاة القادمة": "Next Prayer Time",
        "رفض": "Reject",
        "ملاحظة للمطور": "Note to the developer",
        "الاسم :": "Name :",
        "الملاحظة :": "Note :",
        "ارسال": "Send",
        "الرجاء التأكد من كتابة الاسم": "Please make sure to write the name",
        "الرجاء التأكد من كتابة الملاحظة": "Please make sure to write the note",
        "تم ارسال الرسالة للمطور بنجاح": "The message has been sent to the developer successfully",
        "حدث خطأ ما الرجاء المحاولة مرة اخرى": "An error occurred, please try again",
        "العشاء": "Isha",
        "المغرب": "Maghrib",
        "الفجر": "Fajr",
        "العصر": "Asr",
        "الظهر": "Dhuhr",
        "شروق الشمس": "Sunrise",
        "التاريخ الهجري": "Hijri Date",
        "التاريخ الميلادي": "Gregorian Date",
        "تحديث": "Refresh",
        "اوقات الصلاة": "Prayer Times",
        "الجُزْءُ": "Part",
        "سُورَةُ ": "Surah",
        "إبحث عن آية او سورة...": "Search for an Ayah or Surah...",
        "تعديل نوع الخط": "Change Font Type",
        "حجم الخط": "Font Size",
        "تغير الثيم": "Change Theme",
        "اضافة علامة": "Add Bookmark",
        "لا محدود": "Unlimited",
        "الآية   :  ": "Ayah   :  ",
        "المقطع :  ": "Part   :  ",
        "تكرار التلاوة:  ": "Recitation Repeat:  ",
        "اختر الآية:  ": "Choose Ayah:  ",
        "من الآية:  ": "From Ayah:  ",
        "الى الآية :  ": "To Ayah:  ",
        "تحديد المقطع:": "Choose Part:",
        "القارئ:": "Reader:",
        "اعدادات القراءة": "Recitation Settings",
        "الصفحة": "Page",
        "قم باختيار نوع الخط المناسب لك": "Choose the font type that suits you",
        "الرئيسية": "Home",
        "أسماء الله الحسنى": "Names of Allah",
        "أذكار المسلم": "Muslim Remembrance",
        "مختلف الأذكار": "Various Remembrance",
        "تعرّف على اسماء الله الحسنى": "Learn the names of Allah",
        "سورة ": "Surah",
        "الآية ": "Ayah",
        "حدث خطأ أثناء تشغيل الصوت": "An error occurred while playing the sound",
        "تم تحيل الآية بنجاح": "The Ayah has been bookmarked successfully",
        "مشكلة في الاتصال بالانترنت": "Problem connecting to the Internet",
        "لا يوجد اتصال بالانترنت": "No Internet connection",
        "جاري تحميل الآية": "Loading Ayah",
        "حديث عن رسول الله ﷺ": "Hadith about the Messenger of Allah ﷺ",
        "زاد المؤمن": "Zad Al-Mu'min",
        "تم نسخ النص بنجاح": "The text has been copied successfully",
        "أذكار المنزل": "Home Remembrance",
        "أذكار الاستيقاظ": "Waking Up Remembrance",
        'أذكار النوم': "Sleeping Remembrance",
        'أذكار السفر': "Travel Remembrance",
        'أذكار الطعام': "Eating Remembrance",
        'أذكار المسجد': "Mosque Remembrance",
        'أذكار الخلاء': "Toilet Remembrance",
        'أذكار الحج': "Hajj Remembrance",
        "الكل >>>  ": "All >>>  ",
        " الصفحة ": "Page",
        " الجزء ": "Juz",
        "تم": "Done",
        "بلّغو عني ولوآية": "Report me even with one verse",
        "آية من القرآن الكريم": "A verse from the Holy Quran",
        "الجزء": "Juz",
        "اقسام البرنامج": "Program Sections",
        "تم حذف النص من المفضلة": "The text has been removed from favorites",
        "تم إضافة النص إلى المفضلة": "The text has been added to favorites",
        "الصفحات": "Pages",
        "تم ازالة العلامة": "The bookmark has been removed",
        "تم اضافة العلامة": "The bookmark has been added",
        "الغاء": "Cancel",
        "هل تود ازالة علامة القراءة من هذه الصفحة؟": "Do you want to remove the bookmark from this page?",
        "هل تود وضع علامة على هذه الصفحة؟": "Do you want to add a bookmark to this page?",
        "ازالة علامة قراءة": "Remove Bookmark",
        "اضافة علامة قراءة": "Add Bookmark",
        "ياسر الدوسري": "Yasser Al-Dosari",
        "ياسر السلامة": "Yasser Al-Salamah",
        "ابراهيم الدوسري": "Ibrahim Al-Dosari",
        "أيمن سويد": "Ayman Sowaid",
        "الحصري": "Al-Husari",
        "المنشاوي": "Al-Minshawi",
        "عبد الباسط": "Abdul Basit",
        "العفاسي": "Al-Afasy",
        "عبد الله بصفر": "Abdullah Basfar",
        "ابو بكر الشاطري": "Abu Bakr Al-Shatri",
        "أحمد العجمي": "Ahmed Al-Ajmi",
        "سُورَةُ ٱلْفَاتِحَةِ": "Surat Al-Fatihah",
        "سُورَةُ البَقَرَةِ": "Surat Al-Baqarah",
        "سُورَةُ آلِ عِمْرَانَ": "Surat Al-Imran",
        "سُورَةُ ٱلنِّسَاءِ": "Surat An-Nisa",
        "سُورَةُ ٱلْمَائِدَةِ": "Surat Al-Ma'idah",
        "سُورَةُ ٱلْأَنْعَامِ": "Surat Al-An'am",
        "سُورَةُ ٱلْأَعْرَافِ": "Surat Al-A'raf",
        "سُورَةُ ٱلْأَنْفَالِ": "Surat Al-Anfal",
        "سُورَةُ ٱلتَّوْبَةِ": "Surat At-Tawbah",
        "سُورَةُ يُونُسَ": "Surat Yunus",
        "سُورَةُ هُودٍ": "Surat Hud",
        "سُورَةُ يُوسُفَ": "Surat Yusuf",
        "سُورَةُ ٱلرَّعْدِ": "Surat Ar-Ra'd",
        "سُورَةُ إِبْرَاهِيمَ": "Surat Ibrahim",
        "سُورَةُ ٱلْحِجْرِ": "Surat Al-Hijr",
        "سُورَةُ ٱلنَّحْلِ": "Surat An-Nahl",
        "سُورَةُ ٱلْإِسْرَاءِ": "Surat Al-Isra",
        "سُورَةُ ٱلْكَهْفِ": "Surat Al-Kahf",
        "سُورَةُ مَرْيَمَ": "Surat Maryam",
        "سُورَةُ طه": "Surat Taha",
        "سُورَةُ ٱلْأَنْبِيَاءِ": "Surat Al-Anbiya",
        "سُورَةُ ٱلْحَجِّ": "Surat Al-Hajj",
        "سُورَةُ ٱلْمُؤْمِنُونَ": "Surat Al-Mu'minun",
        "سُورَةُ ٱلنُّورِ": "Surat An-Nur",
        "سُورَةُ ٱلْفُرْقَانِ": "Surat Al-Furqan",
        "سُورَةُ ٱلشُّعَرَاءِ": "Surat Ash-Shu'ara",
        "سُورَةُ ٱلنَّمْلِ": "Surat An-Naml",
        "سُورَةُ ٱلْقَصَصِ": "Surat Al-Qasas",
        "سُورَةُ ٱلْعَنْكَبُوتِ": "Surat Al-Ankabut",
        "سُورَةُ ٱلرُّومِ": "Surat Ar-Rum",
        "سُورَةُ لقمان": "Surat Luqman",
        "سُورَةُ ٱلسَّجْدَةِ": "Surat As-Sajdah",
        "سُورَةُ ٱلْأَحْزَابِ": "Surat Al-Ahzab",
        "سُورَةُ سَبَإٍ": "Surat Saba",
        "سُورَةُ فَاطِرٍ": "Surat Fatir",
        "سُورَةُ يس": "Surat Ya-Sin",
        "سُورَةُ ٱلصَّافَّاتِ": "Surat As-Saffat",
        "سُورَةُ ص": "Surat Sad",
        "سُورَةُ ٱلزُّمَرِ": "Surat Az-Zumar",
        "سُورَةُ غَافِرٍ": "Surat Ghafir",
        "سُورَةُ فُصِّلَتْ": "Surat Fussilat",
        "سُورَةُ ٱلشُّورَىٰ": "Surat Ash-Shura",
        "سُورَةُ ٱلزُّخْرُفِ": "Surat Az-Zukhruf",
        "سُورَةُ ٱلدُّخَانِ": "Surat Ad-Dukhan",
        "سُورَةُ ٱلْجَاثِيَةِ": "Surat Al-Jathiyah",
        "سُورَةُ ٱلْأَحْقَافِ": "Surat Al-Ahqaf",
        "سُورَةُ مُحَمَّدٍ": "Surat Muhammad",
        "سُورَةُ ٱلْفَتْحِ": "Surat Al-Fath",
        "سُورَةُ ٱلْحُجُرَاتِ": "Surat Al-Huj",
        "سُورَةُ ق": "Surat Qaf",
        "سُورَةُ ٱلذَّارِيَاتِ": "Surat Adh-Dhariyat",
        "سُورَةُ ٱلطُّورِ": "Surat At-Tur",
        "سُورَةُ ٱلنَّجْمِ": "Surat An-Najm",
        "سُورَةُ ٱلْقَمَرِ": "Surat Al-Qamar",
        "سُورَةُ ٱلرَّحْمَٰنِ": "Surat Ar-Rahman",
        "سُورَةُ ٱلْوَاقِعَةِ": "Surat Al-Waqi'ah",
        "سُورَةُ ٱلْحَدِيدِ": "Surat Al-Hadid",
        "سُورَةُ ٱلْمُجَادِلَةِ": "Surat Al-Mujadila",
        "سُورَةُ ٱلْحَشْرِ": "Surat Al-Hashr",
        "سُورَةُ ٱلْمُمْتَحَنَةِ": "Surat Al-Mumtahana",
        "سُورَةُ ٱلصَّفِّ": "Surat As-Saff",
        "سُورَةُ ٱلْجُمُعَةِ": "Surat Al-Jumu'ah",
        "سُورَةُ ٱلْمُنَافِقُونَ": "Surat Al-Munafiqun",
        "سُورَةُ ٱلتَّغَابُنِ": "Surat At-Taghabun",
        "سُورَةُ ٱلطَّلَاقِ": "Surat At-Talaq",
        "سُورَةُ ٱلتَّحْرِيمِ": "Surat At-Tahrim",
        "سُورَةُ ٱلْمُلْكِ": "Surat Al-Mulk",
        "سُورَةُ ٱلْقَلَمِ": "Surat Al-Qalam",
        "سُورَةُ ٱلْحَاقَّةِ": "Surat Al-Haqqah",
        "سُورَةُ ٱلْمَعَارِجِ": "Surat Al-Ma'arij",
        "سُورَةُ نُوح": "Surat Nuh",
        "سُورَةُ ٱلْجِنِّ": "Surat Al-Jinn",
        "سُورَةُ ٱلْمُزَّمِّلِ": "Surat Al-Muzzammil",
        "سُورَةُ ٱلْمُدَّثِّرِ": "Surat Al-Muddaththir",
        "سُورَةُ ٱلْقِيَامَةِ": "Surat Al-Qiyamah",
        "سُورَةُ ٱلْإِنسَانِ": "Surat Al-Insan",
        "سُورَةُ ٱلْمُرْسَلَاتِ": "Surat Al-Mursalat",
        "سُورَةُ ٱلنَّبَأِ": "Surat An-Naba",
        "سُورَةُ ٱلنَّازِعَاتِ": "Surat An-Naziat",
        "سُورَةُ عَبَسَ": "Surat Abasa",
        "سُورَةُ ٱلتَّكْوِيرِ": "Surat At-Takwir",
        "سُورَةُ ٱلْإِنفِطَارِ": "Surat Al-Infitar",
        "سُورَةُ ٱلْمُطَفِّفِينَ": "Surat Al-Mutaffifin",
        "سُورَةُ ٱلْإِنشِقَاقِ": "Surat Al-Inshiqaq",
        "سُورَةُ ٱلْبُرُوجِ": "Surat Al-Buruj",
        "سُورَةُ ٱلطَّارِقِ": "Surat At-Tariq",
        "سُورَةُ ٱلْأَعْلَىٰ": "Surat Al-A'la",
        "سُورَةُ ٱلْغَاشِيَةِ": "Surat Al-Ghashiyah",
        "سُورَةُ ٱلْفَجْرِ": "Surat Al-Fajr",
        "سُورَةُ ٱلْبَلَدِ": "Surat Al-Balad",
        "سُورَةُ ٱلشَّمْسِ": "Surat Ash-Shams",
        "سُورَةُ ٱللَّيْلِ": "Surat Al-L",
        "سُورَةُ ٱلضُّحَىٰ": "Surat Ad-Duha",
        "سُورَةُ ٱلشَّرْحِ": "Surat Ash-Sharh",
        "سُورَةُ ٱلتِّينِ": "Surat At-Tin",
        "سُورَةُ ٱلْعَلَقِ": "Surat Al-Alaq",
        "سُورَةُ ٱلْقَدْرِ": "Surat Al-Qadr",
        "سُورَةُ ٱلْبَيِّنَةِ": "Surat Al-Bayyinah",
        "سُورَةُ ٱلزَّلْزَلَةِ": "Surat Az-Zalzalah",
        "سُورَةُ ٱلْعَادِيَاتِ": "Surat Al-Adiyat",
        "سُورَةُ ٱلْقَارِعَةِ": "Surat Al-Qari'ah",
        "سُورَةُ ٱلتَّكَاثُرِ": "Surat At-Takathur",
        "سُورَةُ ٱلْعَصْرِ": "Surat Al-Asr",
        "سُورَةُ ٱلْهُمَزَةِ": "Surat Al-Humazah",
        "سُورَةُ ٱلْفِيلِ": "Surat Al-Fil",
        "سُورَةُ قُرَيْشٍ": "Surat Quraish",
        "سُورَةُ ٱلْمَاعُونَ": "Surat Al-Ma'un",
        "سُورَةُ ٱلْكَوْثَرِ": "Surat Al-Kauthar",
        "سُورَةُ ٱلْكَافِرُونَ": "Surat Al-Kafirun",
        "سُورَةُ ٱلنَّصْرِ": "Surat An-Nasr",
        "سُورَةُ ٱلْمَسَدِ": "Surat Al-Masad",
        "سُورَةُ ٱلْإِخْلَاصِ": "Surat Al-Ikhlas",
        "سُورَةُ ٱلْفَلَقِ": "Surat Al-Falaq",
        "سُورَةُ النَّاسِ": "Surat An-Nas",
        "اللَّهُ": "Allah",
        "وهو الاسم الأعظم الذي تفرد به الحق سبحانه وخص به نفسه وجعله أول أسمائه، وأضافها كلها إليه فهو علم على ذاته سبحانه":
            "And He is the Greatest Name that the Truth has singled out and made it special and made it the first of His names, and added all of them to Him, so He is a science on His own, glory be to Him",
        "الرَّحْمَنُ": "The Most Merciful",
        "كثير الرحمة وهو اسم مقصور على الله عز وجل ولا يجوز أن يقال رحمن لغير الله، وذلك لأن رحمته وسعت كل شيء وهو أرحم الراحمين":
            "He is the Most Merciful, and He is a name that is limited to God Almighty, and it is not permissible to say Rahman for other than God, because His mercy has encompassed everything, and He is the Most Merciful of the Merciful",
        "الرَّحِيمُ": "The Most Gracious",
        "هو المنعم أبدا، المتفضل دوما، فرحمته لا تنتهي":
            "He is the Benefactor forever, the Benefactor always, so His mercy does not end",
        "المَلِكُ": "The King",
        "هو الله، ملك الملوك، له الملك، وهو مالك يوم الدين، ومليك الخلق فهو المالك المطلق":
            "He is God, the King of Kings, to Him is the kingdom, and He is the owner of the Day of Judgment, and the King of creation, so He is the absolute owner",
      };
}
